CREATE OR ALTER PROCEDURE e2x.PopulateStagingLegalEntityCompanies
AS
BEGIN
    SET NOCOUNT ON;

    SELECT *
    INTO #MultiSelectLE
    FROM e2x.vwMultiSelectAgg_LegalEntity_Pivoted;

    CREATE UNIQUE CLUSTERED INDEX IX_tmp_MultiSelectLE
        ON #MultiSelectLE (PrimaryId);

    TRUNCATE TABLE e2x.StagingLegalEntityCompanies;

    INSERT INTO e2x.StagingLegalEntityCompanies
    (
        [LegalEntityId],
        [AlternateId],
        [IsCustomer],
        [Name],
        [FenESubTypeId],
        [FenESubType],
        [FenXSubType],
        [LEI],
        [FenELegalEntityCategoryId],
        [FenELegalEntityCategory],
        [FenXLegalEntityCategory],
        [FenENaicsId],
        [FenENaics],
        [FenXNaics],
        [FenEIsicId],
        [FenEIsic],
        [FenXIsic],
        [DateOfIncorporationEstablishment],
        [FenECountryOfIncorporationEstablishmentId],
        [FenECountryOfIncorporationEstablishment],
        [FenXCountryOfIncorporationEstablishment],
        [FenECountryOfDomicileId],
        [FenECountryOfDomicile],
        [FenXCountryOfDomicile],
        [FenEMoneyServicesBusinessId],
        [FenEMoneyServicesBusiness],
        [FenXMoneyServicesBusiness],
        [FenEIsTheEntityRegulatedId],
        [FenEIsTheEntityRegulated],
        [FenXIsTheEntityRegulated],
        [FenEIsTheEntityAWhollyOwnedSubsidiaryOfAParentId],
        [FenEIsTheEntityAWhollyOwnedSubsidiaryOfAParent],
        [FenXIsTheEntityAWhollyOwnedSubsidiaryOfAParent],
        [FenEParentCompanyCountryOfIncorporationId],
        [FenEParentCompanyCountryOfIncorporation],
        [FenXParentCompanyCountryOfIncorporation],
        [FenEIsTheParentEntityRegulatedId],
        [FenEIsTheParentEntityRegulated],
        [FenXIsTheParentEntityRegulated],
        [FenEParentRegulatedById],
        [FenEParentRegulatedBy],
        [FenXParentRegulatedBy],
        [FenEParentSAmlGuidelinesReviewedAndApprovedId],
        [FenEParentSAmlGuidelinesReviewedAndApproved],
        [FenXParentSAmlGuidelinesReviewedAndApproved],
        [FenENameOfExchangesTheParentEntityIsListedOnIds],
        [FenENameOfExchangesTheParentEntityIsListedOn],
        [FenXNameOfExchangesTheParentEntityIsListedOn],
        [FenECanTheCorporationIssueBearerSharesId],
        [FenECanTheCorporationIssueBearerShares],
        [FenXCanTheCorporationIssueBearerShares],
        [FenEIsTheAdministratorRegulatedId],
        [FenEIsTheAdministratorRegulated],
        [FenXIsTheAdministratorRegulated],
        [FenEIsTheInvestmentAdviserRegulatedId],
        [FenEIsTheInvestmentAdviserRegulated],
        [FenXIsTheInvestmentAdviserRegulated],
        [FenEIsTheInvestmentManagerRegulatedId],
        [FenEIsTheInvestmentManagerRegulated],
        [FenXIsTheInvestmentManagerRegulated],
        [FenERegulatedByIds],
        [FenERegulatedBy],
        [FenXRegulatedBy],
        [RegulatoryId],
        [FenEIsThereAnAmlProgramInPlaceId],
        [FenEIsThereAnAmlProgramInPlace],
        [FenXIsThereAnAmlProgramInPlace],
        [FenEPrincipalPlaceOfBusinessId],
        [FenEPrincipalPlaceOfBusiness],
        [FenXPrincipalPlaceOfBusiness],
        [FenETypeOfInvestorId],
        [FenETypeOfInvestor],
        [FenXTypeOfInvestor],
        [FenEApplicableVeryHighRiskIndustryId],
        [FenEApplicableVeryHighRiskIndustry],
        [FenXApplicableVeryHighRiskIndustry],
        [FenEEnterpriseSicId],
        [FenEEnterpriseSic],
        [FenXEnterpriseSic],
        [FenEApplicableEntityTypeId],
        [FenEApplicableEntityType],
        [FenXApplicableEntityType],
        [FenEPepControlledEntityId],
        [FenEPepControlledEntity],
        [FenXPepControlledEntity],
        [FenEMaterialNegativeNewsId],
        [FenEMaterialNegativeNews],
        [FenXMaterialNegativeNews],
        [FenEIsThisACustomerOfConcernId],
        [FenEIsThisACustomerOfConcern],
        [FenXIsThisACustomerOfConcern],
        [FenEGlobalModelExclusionsIds],
        [FenEGlobalModelExclusions],
        [FenXGlobalModelExclusions],
        [FenESpecializedEddRequiredId],
        [FenESpecializedEddRequired],
        [FenXSpecializedEddRequired],
        [FenESpecializedEddEntityTypeIds],
        [FenESpecializedEddEntityType],
        [FenXSpecializedEddEntityType],
        [RiskCategory],
        [FenEKycLevelId],
        [FenEKycLevel],
        [FenXKycLevel],
        [KycLevelOverrideComment],
        [FenEEntityTypeId],
        [FenEEntityType],
        [FenXEntityType],
        [RegistrationNumber],
        [RegistrationBody],
        [OperatingTradingName],
        [FenEPreviousNameId],
        [FenEPreviousName],
        [FenXPreviousName],
        [Website],
        [DateOfEstablishment],
        [AccountActivityReview],
        [NatureOfActivityBusiness],
        [PartnershipType],
        [FenELegalStatusId],
        [FenELegalStatus],
        [FenXLegalStatus],
        [Ltid],
        [FenERegulatoryStatusIds],
        [FenERegulatoryStatus],
        [FenXRegulatoryStatus],
        [FenEApplicableExemptionCategoriesIds],
        [FenEApplicableExemptionCategories],
        [FenXApplicableExemptionCategories],
        [FenENameOfExchangesTheEntityIsListedOnIds],
        [FenENameOfExchangesTheEntityIsListedOn],
        [FenXNameOfExchangesTheEntityIsListedOn],
        [FenEKycClientTypeId],
        [FenEKycClientType],
        [FenXKycClientType],
        [FenEAdministratorRegulatedById],
        [FenEAdministratorRegulatedBy],
        [FenXAdministratorRegulatedBy],
        [FenEInvestmentAdviserRegulatedById],
        [FenEInvestmentAdviserRegulatedBy],
        [FenXInvestmentAdviserRegulatedBy],
        [FenEInvestmentManagerRegulatedById],
        [FenEInvestmentManagerRegulatedBy],
        [FenXInvestmentManagerRegulatedBy],
        [AnticipatedActivityOfAccount],
        [DoesTheEntityHaveAPreviousNames],
        [DateOfLastNameChange],
        [FenEThirdPartyAccountId],
        [FenEThirdPartyAccount],
        [FenXThirdPartyAccount],
        [DateOfIncorporation],
        [FenEPrimaryBusinessLocationId],
        [FenEPrimaryBusinessLocation],
        [FenXPrimaryBusinessLocation],
        [FenELocationOfBusinessActivityId],
        [FenELocationOfBusinessActivity],
        [FenXLocationOfBusinessActivity],
        [FenEIsItConsideredACorporationId],
        [FenEIsItConsideredACorporation],
        [FenXIsItConsideredACorporation],
        [FenEPartnershipsCustodianHasAssumedWithholdingId],
        [FenEPartnershipsCustodianHasAssumedWithholding],
        [FenXPartnershipsCustodianHasAssumedWithholding],
        [FenEElectedToBeTreatedAsACorporationUnderUSTaxLawId],
        [FenEElectedToBeTreatedAsACorporationUnderUSTaxLaw],
        [FenXElectedToBeTreatedAsACorporationUnderUSTaxLaw],
        [FenEConsideredAsAWithholdingForeignPartnershipUnderUSTaxLawId],
        [FenEConsideredAsAWithholdingForeignPartnershipUnderUSTaxLaw],
        [FenXConsideredAsAWithholdingForeignPartnershipUnderUSTaxLaw],
        [FenEHas25OrFewerPartnersAndIsConsideredAsAPartnershipUnderUSTaxLawId],
        [FenEHas25OrFewerPartnersAndIsConsideredAsAPartnershipUnderUSTaxLaw],
        [FenXHas25OrFewerPartnersAndIsConsideredAsAPartnershipUnderUSTaxLaw],
        [FenEContainsNonCanadianPartnersId],
        [FenEContainsNonCanadianPartners],
        [FenXContainsNonCanadianPartners],
        [FenEComplexTrustUnderUSTaxLawId],
        [FenEComplexTrustUnderUSTaxLaw],
        [FenXComplexTrustUnderUSTaxLaw],
        [FenETheAuthorizedTrusteeIsACanadianRegistrantFinancialInstitutionId],
        [FenETheAuthorizedTrusteeIsACanadianRegistrantFinancialInstitution],
        [FenXTheAuthorizedTrusteeIsACanadianRegistrantFinancialInstitution],
        [FenETrustIsRegisteredWithIrsAsAWithholdingForeignTrustId],
        [FenETrustIsRegisteredWithIrsAsAWithholdingForeignTrust],
        [FenXTrustIsRegisteredWithIrsAsAWithholdingForeignTrust],
        [FenETrustOrDesignatedCustodianHaveAssumedWithholdingId],
        [FenETrustOrDesignatedCustodianHaveAssumedWithholding],
        [FenXTrustOrDesignatedCustodianHaveAssumedWithholding],
        [FenEIsTheTrustCompanyRegisteredForTrustBusinessId],
        [FenEIsTheTrustCompanyRegisteredForTrustBusiness],
        [FenXIsTheTrustCompanyRegisteredForTrustBusiness],
        [RegisteredWith],
        [PrimaryBusinessActivity],
        [NatureOfFunding],
        [StructureType],
        [FenENationalGovernmentId],
        [FenENationalGovernment],
        [FenXNationalGovernment],
        [NameOfHomeStateAuthority],
        [FenEDoesTheCharitySolicitDonationsId],
        [FenEDoesTheCharitySolicitDonations],
        [FenXDoesTheCharitySolicitDonations],
        [PensionSchemeRegistrationNumber],
        [FenEAreContributionsMadeByTheEmployerSettingUpTheSchemeId],
        [FenEAreContributionsMadeByTheEmployerSettingUpTheScheme],
        [FenXAreContributionsMadeByTheEmployerSettingUpTheScheme],
        [NameOfPensionSchemeAdministrator],
        [NameOfPensionSchemePromoter],
        [NameOfPensionSchemeSponsor],
        [FenENace2CodeId],
        [FenENace2Code],
        [FenXNace2Code],
        [StockExchangeCode],
        [CentralIndexKey],
        [SwiftBic],
        [FenENaicsCodeId],
        [FenENaicsCode],
        [FenXNaicsCode],
        [FenEIscId],
        [FenEIsc],
        [FenXIsc],
        [LengthOfRelationshipWithScotiabank],
        [FenENegativeNewsScreeningConductedId],
        [FenENegativeNewsScreeningConducted],
        [FenXNegativeNewsScreeningConducted],
        [SummaryOfBusinessActivitiesWithScotia],
        [AnnualRevenueUsdMillions],
        [BusinessChangesMadeInTheLast5Years],
        [BusinessDescription],
        [NumberOfEmployees],
        [PrimaryCustomerBase],
        [PrimaryRevenueGeneratingProductsAndServices],
        [FenESignificantCustomerCountriesIds],
        [FenESignificantCustomerCountries],
        [FenXSignificantCustomerCountries],
        [FenESignificantRevenueCountriesIds],
        [FenESignificantRevenueCountries],
        [FenXSignificantRevenueCountries],
        [FenESignificantSupplierCountriesIds],
        [FenESignificantSupplierCountries],
        [FenXSignificantSupplierCountries],
        [LoadTimestamp]
    )
    SELECT
        le.Id AS LegalEntityId,
        CAST(le.Id AS VARCHAR(50)) AS AlternateId,
        CASE WHEN EXISTS (SELECT 1 FROM dbo.LEAssociate AS ler WHERE ler.LegalEntityId = le.Id AND ler.Active = 1 AND ler.LEAssociateTypeID = 101 AND ler.LegalEntityRoleStatusId IN (1,3)) THEN 1 ELSE 0 END AS IsCustomer,
        le.[Name],
        le.LegalEntitySubtypeId AS FenESubTypeId,
        lookupSubType.EValue AS FenESubType,
        lookupSubType.XValue AS FenXSubType,
        lec.LEI AS LEI,
        le.[Category] AS [FenELegalEntityCategoryId],
        lookupLegalEntityCategory1.EValue AS [FenELegalEntityCategory],
        lookupLegalEntityCategory1.XValue AS [FenXLegalEntityCategory],
        lec.[NaicCode] AS [FenENaicsId],
        lookupNaics2.EValue AS [FenENaics],
        lookupNaics2.XValue AS [FenXNaics],
        lec.[Isic] AS [FenEIsicId],
        lookupIsic3.EValue AS [FenEIsic],
        lookupIsic3.XValue AS [FenXIsic],
        lec.[DateOfIncorporation] AS [DateOfIncorporationEstablishment],
        lec.[CountryOfIncorporationId] AS [FenECountryOfIncorporationEstablishmentId],
        lookupCountryOfIncorporationEstablishment4.EValue AS [FenECountryOfIncorporationEstablishment],
        lookupCountryOfIncorporationEstablishment4.XValue AS [FenXCountryOfIncorporationEstablishment],
        le.[NationalCountryId] AS [FenECountryOfDomicileId],
        lookupCountryOfDomicile5.EValue AS [FenECountryOfDomicile],
        lookupCountryOfDomicile5.XValue AS [FenXCountryOfDomicile],
        lec.[IsMoneyServicesBusiness] AS [FenEMoneyServicesBusinessId],
        lookupMoneyServicesBusiness6.EValue AS [FenEMoneyServicesBusiness],
        lookupMoneyServicesBusiness6.XValue AS [FenXMoneyServicesBusiness],
        lec.[IsRegulated] AS [FenEIsTheEntityRegulatedId],
        lookupIsTheEntityRegulated7.EValue AS [FenEIsTheEntityRegulated],
        lookupIsTheEntityRegulated7.XValue AS [FenXIsTheEntityRegulated],
        lec.[IsWhollyOwnedByParent] AS [FenEIsTheEntityAWhollyOwnedSubsidiaryOfAParentId],
        lookupIsTheEntityAWhollyOwnedSubsidiaryOfAParent8.EValue AS [FenEIsTheEntityAWhollyOwnedSubsidiaryOfAParent],
        lookupIsTheEntityAWhollyOwnedSubsidiaryOfAParent8.XValue AS [FenXIsTheEntityAWhollyOwnedSubsidiaryOfAParent],
        lec.[ParentCompanyCOI] AS [FenEParentCompanyCountryOfIncorporationId],
        lookupParentCompanyCountryOfIncorporation9.EValue AS [FenEParentCompanyCountryOfIncorporation],
        lookupParentCompanyCountryOfIncorporation9.XValue AS [FenXParentCompanyCountryOfIncorporation],
        lec.[IsParentRegulated] AS [FenEIsTheParentEntityRegulatedId],
        lookupIsTheParentEntityRegulated10.EValue AS [FenEIsTheParentEntityRegulated],
        lookupIsTheParentEntityRegulated10.XValue AS [FenXIsTheParentEntityRegulated],
        lec.[ParentRegulatedBy] AS [FenEParentRegulatedById],
        lookupParentRegulatedBy11.EValue AS [FenEParentRegulatedBy],
        lookupParentRegulatedBy11.XValue AS [FenXParentRegulatedBy],
        lec.[IsGuidelinesApproved] AS [FenEParentSAmlGuidelinesReviewedAndApprovedId],
        lookupParentSAmlGuidelinesReviewedAndApproved12.EValue AS [FenEParentSAmlGuidelinesReviewedAndApproved],
        lookupParentSAmlGuidelinesReviewedAndApproved12.XValue AS [FenXParentSAmlGuidelinesReviewedAndApproved],
        msaLE.FenENameOfExchangesTheParentEntityIsListedOnIds AS [FenENameOfExchangesTheParentEntityIsListedOnIds],
        msaLE.FenENameOfExchangesTheParentEntityIsListedOn AS [FenENameOfExchangesTheParentEntityIsListedOn],
        msaLE.FenXNameOfExchangesTheParentEntityIsListedOn AS [FenXNameOfExchangesTheParentEntityIsListedOn],
        lec.[CanIssueBearerShares] AS [FenECanTheCorporationIssueBearerSharesId],
        lookupCanTheCorporationIssueBearerShares13.EValue AS [FenECanTheCorporationIssueBearerShares],
        lookupCanTheCorporationIssueBearerShares13.XValue AS [FenXCanTheCorporationIssueBearerShares],
        lec.[IsAdministratorRegulated] AS [FenEIsTheAdministratorRegulatedId],
        lookupIsTheAdministratorRegulated14.EValue AS [FenEIsTheAdministratorRegulated],
        lookupIsTheAdministratorRegulated14.XValue AS [FenXIsTheAdministratorRegulated],
        lec.[IsAdviserRegulated] AS [FenEIsTheInvestmentAdviserRegulatedId],
        lookupIsTheInvestmentAdviserRegulated15.EValue AS [FenEIsTheInvestmentAdviserRegulated],
        lookupIsTheInvestmentAdviserRegulated15.XValue AS [FenXIsTheInvestmentAdviserRegulated],
        lec.[IsManagerRegulated] AS [FenEIsTheInvestmentManagerRegulatedId],
        lookupIsTheInvestmentManagerRegulated16.EValue AS [FenEIsTheInvestmentManagerRegulated],
        lookupIsTheInvestmentManagerRegulated16.XValue AS [FenXIsTheInvestmentManagerRegulated],
        msaLE.FenERegulatedByIds AS [FenERegulatedByIds],
        msaLE.FenERegulatedBy AS [FenERegulatedBy],
        msaLE.FenXRegulatedBy AS [FenXRegulatedBy],
        lec.[RegulatoryID] AS [RegulatoryId],
        lec.[IsThereAMLApproved] AS [FenEIsThereAnAmlProgramInPlaceId],
        lookupIsThereAnAmlProgramInPlace17.EValue AS [FenEIsThereAnAmlProgramInPlace],
        lookupIsThereAnAmlProgramInPlace17.XValue AS [FenXIsThereAnAmlProgramInPlace],
        lec.[PrincipalPlaceBusinessId] AS [FenEPrincipalPlaceOfBusinessId],
        lookupPrincipalPlaceOfBusiness18.EValue AS [FenEPrincipalPlaceOfBusiness],
        lookupPrincipalPlaceOfBusiness18.XValue AS [FenXPrincipalPlaceOfBusiness],
        lex.[TypeOfInvestorId] AS [FenETypeOfInvestorId],
        lookupTypeOfInvestor19.EValue AS [FenETypeOfInvestor],
        lookupTypeOfInvestor19.XValue AS [FenXTypeOfInvestor],
        lex.[ApplicableVeryHighRiskIndustryId] AS [FenEApplicableVeryHighRiskIndustryId],
        lookupApplicableVeryHighRiskIndustry20.EValue AS [FenEApplicableVeryHighRiskIndustry],
        lookupApplicableVeryHighRiskIndustry20.XValue AS [FenXApplicableVeryHighRiskIndustry],
        lec.[LookupSicCodeId] AS [FenEEnterpriseSicId],
        lookupEnterpriseSic21.EValue AS [FenEEnterpriseSic],
        lookupEnterpriseSic21.XValue AS [FenXEnterpriseSic],
        lex.[ApplicableEntityTypeId] AS [FenEApplicableEntityTypeId],
        lookupApplicableEntityType22.EValue AS [FenEApplicableEntityType],
        lookupApplicableEntityType22.XValue AS [FenXApplicableEntityType],
        lex.[PEPControlledEntityId] AS [FenEPepControlledEntityId],
        lookupPepControlledEntity23.EValue AS [FenEPepControlledEntity],
        lookupPepControlledEntity23.XValue AS [FenXPepControlledEntity],
        lex.[MaterialNegativeNewsId] AS [FenEMaterialNegativeNewsId],
        lookupMaterialNegativeNews24.EValue AS [FenEMaterialNegativeNews],
        lookupMaterialNegativeNews24.XValue AS [FenXMaterialNegativeNews],
        lex.[IsthisCustomerConcernId] AS [FenEIsThisACustomerOfConcernId],
        lookupIsThisACustomerOfConcern25.EValue AS [FenEIsThisACustomerOfConcern],
        lookupIsThisACustomerOfConcern25.XValue AS [FenXIsThisACustomerOfConcern],
        msaLE.FenEGlobalModelExclusionsIds AS [FenEGlobalModelExclusionsIds],
        msaLE.FenEGlobalModelExclusions AS [FenEGlobalModelExclusions],
        msaLE.FenXGlobalModelExclusions AS [FenXGlobalModelExclusions],
        lex.[SpecEDDRequiredId] AS [FenESpecializedEddRequiredId],
        lookupSpecializedEddRequired26.EValue AS [FenESpecializedEddRequired],
        lookupSpecializedEddRequired26.XValue AS [FenXSpecializedEddRequired],
        msaLE.FenESpecializedEddEntityTypeIds AS [FenESpecializedEddEntityTypeIds],
        msaLE.FenESpecializedEddEntityType AS [FenESpecializedEddEntityType],
        msaLE.FenXSpecializedEddEntityType AS [FenXSpecializedEddEntityType],
        risk.[DerivedRiskOutcome] AS [RiskCategory],
        le.[KYCLevelId] AS [FenEKycLevelId],
        lookupKycLevel27.EValue AS [FenEKycLevel],
        lookupKycLevel27.XValue AS [FenXKycLevel],
        le.[KYCOverrideComment] AS [KycLevelOverrideComment],
        lec.[EntityType] AS [FenEEntityTypeId],
        lookupEntityType28.EValue AS [FenEEntityType],
        lookupEntityType28.XValue AS [FenXEntityType],
        lec.[RegistrationNumber] AS [RegistrationNumber],
        lek.[RegisteredBy] AS [RegistrationBody],
        lec.[OperatingName] AS [OperatingTradingName],
        lek.[EntityHavePreviousNameId] AS [FenEPreviousNameId],
        lookupPreviousName29.EValue AS [FenEPreviousName],
        lookupPreviousName29.XValue AS [FenXPreviousName],
        lex.[Website] AS [Website],
        lek.[DateOfEstablishment] AS [DateOfEstablishment],
        lex.[AccountActivityReview] AS [AccountActivityReview],
        lex.[NatureOfActivityBusiness] AS [NatureOfActivityBusiness],
        lec.[PartnershipType] AS [PartnershipType],
        lec.[LegalStatusId] AS [FenELegalStatusId],
        lookupLegalStatus30.EValue AS [FenELegalStatus],
        lookupLegalStatus30.XValue AS [FenXLegalStatus],
        lex.[LTID] AS [Ltid],
        msaLE.FenERegulatoryStatusIds AS [FenERegulatoryStatusIds],
        msaLE.FenERegulatoryStatus AS [FenERegulatoryStatus],
        msaLE.FenXRegulatoryStatus AS [FenXRegulatoryStatus],
        msaLE.FenEApplicableExemptionCategoriesIds AS [FenEApplicableExemptionCategoriesIds],
        msaLE.FenEApplicableExemptionCategories AS [FenEApplicableExemptionCategories],
        msaLE.FenXApplicableExemptionCategories AS [FenXApplicableExemptionCategories],
        msaLE.FenENameOfExchangesTheEntityIsListedOnIds AS [FenENameOfExchangesTheEntityIsListedOnIds],
        msaLE.FenENameOfExchangesTheEntityIsListedOn AS [FenENameOfExchangesTheEntityIsListedOn],
        msaLE.FenXNameOfExchangesTheEntityIsListedOn AS [FenXNameOfExchangesTheEntityIsListedOn],
        le.[ClientType] AS [FenEKycClientTypeId],
        lookupKycClientType31.EValue AS [FenEKycClientType],
        lookupKycClientType31.XValue AS [FenXKycClientType],
        lec.[AdministratorRegulatedBy] AS [FenEAdministratorRegulatedById],
        lookupAdministratorRegulatedBy32.EValue AS [FenEAdministratorRegulatedBy],
        lookupAdministratorRegulatedBy32.XValue AS [FenXAdministratorRegulatedBy],
        lec.[AdviserRegulatedBy] AS [FenEInvestmentAdviserRegulatedById],
        lookupInvestmentAdviserRegulatedBy33.EValue AS [FenEInvestmentAdviserRegulatedBy],
        lookupInvestmentAdviserRegulatedBy33.XValue AS [FenXInvestmentAdviserRegulatedBy],
        lec.[ManagerRegulatedBy] AS [FenEInvestmentManagerRegulatedById],
        lookupInvestmentManagerRegulatedBy34.EValue AS [FenEInvestmentManagerRegulatedBy],
        lookupInvestmentManagerRegulatedBy34.XValue AS [FenXInvestmentManagerRegulatedBy],
        lek.[AnticipatedActivityAccount] AS [AnticipatedActivityOfAccount],
        lec.[PreviousNames] AS [DoesTheEntityHaveAPreviousNames],
        lec.[PreviousNameDate] AS [DateOfLastNameChange],
        lex.[ThirdPartyAccount] AS [FenEThirdPartyAccountId],
        lookupThirdPartyAccount35.EValue AS [FenEThirdPartyAccount],
        lookupThirdPartyAccount35.XValue AS [FenXThirdPartyAccount],
        lec.[DateOfIncorporation] AS [DateOfIncorporation],
        lec.[PrimaryBusinessLocationId] AS [FenEPrimaryBusinessLocationId],
        lookupPrimaryBusinessLocation36.EValue AS [FenEPrimaryBusinessLocation],
        lookupPrimaryBusinessLocation36.XValue AS [FenXPrimaryBusinessLocation],
        lec.[LocationBusinessActivity] AS [FenELocationOfBusinessActivityId],
        lookupLocationOfBusinessActivity37.EValue AS [FenELocationOfBusinessActivity],
        lookupLocationOfBusinessActivity37.XValue AS [FenXLocationOfBusinessActivity],
        lecex.[IsCorporation] AS [FenEIsItConsideredACorporationId],
        lookupIsItConsideredACorporation38.EValue AS [FenEIsItConsideredACorporation],
        lookupIsItConsideredACorporation38.XValue AS [FenXIsItConsideredACorporation],
        lecex.[PartCustodianUSSI] AS [FenEPartnershipsCustodianHasAssumedWithholdingId],
        lookupPartnershipsCustodianHasAssumedWithholding39.EValue AS [FenEPartnershipsCustodianHasAssumedWithholding],
        lookupPartnershipsCustodianHasAssumedWithholding39.XValue AS [FenXPartnershipsCustodianHasAssumedWithholding],
        lecex.[ElectedCorporationUSTL] AS [FenEElectedToBeTreatedAsACorporationUnderUSTaxLawId],
        lookupElectedToBeTreatedAsACorporationUnderUSTaxLaw40.EValue AS [FenEElectedToBeTreatedAsACorporationUnderUSTaxLaw],
        lookupElectedToBeTreatedAsACorporationUnderUSTaxLaw40.XValue AS [FenXElectedToBeTreatedAsACorporationUnderUSTaxLaw],
        lecex.[ConsWithholdForeignPartUSTL] AS [FenEConsideredAsAWithholdingForeignPartnershipUnderUSTaxLawId],
        lookupConsideredAsAWithholdingForeignPartnershipUnderUSTaxLaw41.EValue AS [FenEConsideredAsAWithholdingForeignPartnershipUnderUSTaxLaw],
        lookupConsideredAsAWithholdingForeignPartnershipUnderUSTaxLaw41.XValue AS [FenXConsideredAsAWithholdingForeignPartnershipUnderUSTaxLaw],
        lecex.[Less25PartnersConsPartnershipUSTL] AS [FenEHas25OrFewerPartnersAndIsConsideredAsAPartnershipUnderUSTaxLawId],
        lookupHas25OrFewerPartnersAndIsConsideredAsAPartnershipUnderUSTaxLaw42.EValue AS [FenEHas25OrFewerPartnersAndIsConsideredAsAPartnershipUnderUSTaxLaw],
        lookupHas25OrFewerPartnersAndIsConsideredAsAPartnershipUnderUSTaxLaw42.XValue AS [FenXHas25OrFewerPartnersAndIsConsideredAsAPartnershipUnderUSTaxLaw],
        lecex.[ContNonCanadPartners] AS [FenEContainsNonCanadianPartnersId],
        lookupContainsNonCanadianPartners43.EValue AS [FenEContainsNonCanadianPartners],
        lookupContainsNonCanadianPartners43.XValue AS [FenXContainsNonCanadianPartners],
        lecex.[ComplexTrustUnderUSTL] AS [FenEComplexTrustUnderUSTaxLawId],
        lookupComplexTrustUnderUSTaxLaw44.EValue AS [FenEComplexTrustUnderUSTaxLaw],
        lookupComplexTrustUnderUSTaxLaw44.XValue AS [FenXComplexTrustUnderUSTaxLaw],
        lecex.[AuthTrusteeIsCanRegistrant] AS [FenETheAuthorizedTrusteeIsACanadianRegistrantFinancialInstitutionId],
        lookupTheAuthorizedTrusteeIsACanadianRegistrantFinancialInstitution45.EValue AS [FenETheAuthorizedTrusteeIsACanadianRegistrantFinancialInstitution],
        lookupTheAuthorizedTrusteeIsACanadianRegistrantFinancialInstitution45.XValue AS [FenXTheAuthorizedTrusteeIsACanadianRegistrantFinancialInstitution],
        lecex.[TrustRegIRSAsWFT] AS [FenETrustIsRegisteredWithIrsAsAWithholdingForeignTrustId],
        lookupTrustIsRegisteredWithIrsAsAWithholdingForeignTrust46.EValue AS [FenETrustIsRegisteredWithIrsAsAWithholdingForeignTrust],
        lookupTrustIsRegisteredWithIrsAsAWithholdingForeignTrust46.XValue AS [FenXTrustIsRegisteredWithIrsAsAWithholdingForeignTrust],
        lecex.[TrustAssumedWithholdingUSSI] AS [FenETrustOrDesignatedCustodianHaveAssumedWithholdingId],
        lookupTrustOrDesignatedCustodianHaveAssumedWithholding47.EValue AS [FenETrustOrDesignatedCustodianHaveAssumedWithholding],
        lookupTrustOrDesignatedCustodianHaveAssumedWithholding47.XValue AS [FenXTrustOrDesignatedCustodianHaveAssumedWithholding],
        lec.[IsTrustCompanyRegistered] AS [FenEIsTheTrustCompanyRegisteredForTrustBusinessId],
        lookupIsTheTrustCompanyRegisteredForTrustBusiness48.EValue AS [FenEIsTheTrustCompanyRegisteredForTrustBusiness],
        lookupIsTheTrustCompanyRegisteredForTrustBusiness48.XValue AS [FenXIsTheTrustCompanyRegisteredForTrustBusiness],
        lec.[RegisteredWith] AS [RegisteredWith],
        lec.[PrimaryBusinessActivity] AS [PrimaryBusinessActivity],
        lec.[Nature] AS [NatureOfFunding],
        lec.[StructureType] AS [StructureType],
        lec.[NationalGovernment] AS [FenENationalGovernmentId],
        lookupNationalGovernment49.EValue AS [FenENationalGovernment],
        lookupNationalGovernment49.XValue AS [FenXNationalGovernment],
        lec.[NameOfHomeStateAuthority] AS [NameOfHomeStateAuthority],
        lec.[SolicitsDonations] AS [FenEDoesTheCharitySolicitDonationsId],
        lookupDoesTheCharitySolicitDonations50.EValue AS [FenEDoesTheCharitySolicitDonations],
        lookupDoesTheCharitySolicitDonations50.XValue AS [FenXDoesTheCharitySolicitDonations],
        lex.[LengthRelationship] AS [PensionSchemeRegistrationNumber],
        lex.[NegNewsScreenConducted] AS [FenEAreContributionsMadeByTheEmployerSettingUpTheSchemeId],
        lookupAreContributionsMadeByTheEmployerSettingUpTheScheme51.EValue AS [FenEAreContributionsMadeByTheEmployerSettingUpTheScheme],
        lookupAreContributionsMadeByTheEmployerSettingUpTheScheme51.XValue AS [FenXAreContributionsMadeByTheEmployerSettingUpTheScheme],
        lex.[SumBusActWithScotia] AS [NameOfPensionSchemeAdministrator],
        lex.[PrimaryRevGenProdServ] AS [NameOfPensionSchemePromoter],
        lec.[NameOfPlanSponsor] AS [NameOfPensionSchemeSponsor],
        lec.[Nace] AS [FenENace2CodeId],
        lookupNace2Code52.EValue AS [FenENace2Code],
        lookupNace2Code52.XValue AS [FenXNace2Code],
        lec.[TickerCode] AS [StockExchangeCode],
        lec.[CIK] AS [CentralIndexKey],
        lec.[Swift] AS [SwiftBic],
        lec.[NaicCode] AS [FenENaicsCodeId],
        lookupNaicsCode53.EValue AS [FenENaicsCode],
        lookupNaicsCode53.XValue AS [FenXNaicsCode],
        lec.[ISCCode] AS [FenEIscId],
        lookupIsc54.EValue AS [FenEIsc],
        lookupIsc54.XValue AS [FenXIsc],
        lex.[LengthRelationship] AS [LengthOfRelationshipWithScotiabank],
        lex.[NegNewsScreenConducted] AS [FenENegativeNewsScreeningConductedId],
        lookupNegativeNewsScreeningConducted55.EValue AS [FenENegativeNewsScreeningConducted],
        lookupNegativeNewsScreeningConducted55.XValue AS [FenXNegativeNewsScreeningConducted],
        lex.[SumBusActWithScotia] AS [SummaryOfBusinessActivitiesWithScotia],
        lecex.[AnnualRevenue] AS [AnnualRevenueUsdMillions],
        lecex.[BusChangesLast5Years] AS [BusinessChangesMadeInTheLast5Years],
        lecex.[BusDescription] AS [BusinessDescription],
        lecex.[NumEmployees] AS [NumberOfEmployees],
        lecex.[PrimaryCustomerBase] AS [PrimaryCustomerBase],
        lex.[PrimaryRevGenProdServ] AS [PrimaryRevenueGeneratingProductsAndServices],
        msaLE.FenESignificantCustomerCountriesIds AS [FenESignificantCustomerCountriesIds],
        msaLE.FenESignificantCustomerCountries AS [FenESignificantCustomerCountries],
        msaLE.FenXSignificantCustomerCountries AS [FenXSignificantCustomerCountries],
        msaLE.FenESignificantRevenueCountriesIds AS [FenESignificantRevenueCountriesIds],
        msaLE.FenESignificantRevenueCountries AS [FenESignificantRevenueCountries],
        msaLE.FenXSignificantRevenueCountries AS [FenXSignificantRevenueCountries],
        msaLE.FenESignificantSupplierCountriesIds AS [FenESignificantSupplierCountriesIds],
        msaLE.FenESignificantSupplierCountries AS [FenESignificantSupplierCountries],
        msaLE.FenXSignificantSupplierCountries AS [FenXSignificantSupplierCountries],
        CURRENT_TIMESTAMP AS LoadTimestamp
    FROM dbo.LegalEntity AS le
    LEFT JOIN dbo.LECompany AS lec ON lec.LegalEntityId = le.Id
    LEFT JOIN e2x.Lookups AS lookupSubType ON lookupSubType.LookupName = 'LuLeSubTpWithUndefined' AND lookupSubType.EId = le.LegalEntitySubtypeId
    LEFT JOIN dbo.LegalEntityKYC AS lek ON lek.LegalEntityId = le.Id
    LEFT JOIN scotia.LegalEntityExtension AS lex ON lex.LegalEntityId = le.Id
    LEFT JOIN scotia.LECompanyExtension AS lecex ON lecex.LegalEntityId = le.Id
    LEFT JOIN #MultiSelectLE AS msaLE
        ON msaLE.PrimaryId = le.Id
    OUTER APPLY
    (
        SELECT TOP (1)
               cdr.DerivedRiskOutcome
        FROM rr.CrrCaseDerivedRisk AS cdr
        WHERE cdr.EntityId = le.Id
          AND cdr.BusinessEntityTypeId = 30
          AND cdr.CaseId IS NULL
        ORDER BY cdr.Id DESC
    ) AS risk
    LEFT JOIN e2x.Lookups AS lookupLegalEntityCategory1 ON lookupLegalEntityCategory1.LookupName = 'LECategory' AND lookupLegalEntityCategory1.EId = le.[Category]
    LEFT JOIN e2x.Lookups AS lookupNaics2 ON lookupNaics2.LookupName = 'NaicCodeDescription' AND lookupNaics2.EId = lec.[NaicCode]
    LEFT JOIN e2x.Lookups AS lookupIsic3 ON lookupIsic3.LookupName = 'IsicCodeDescription' AND lookupIsic3.EId = lec.[Isic]
    LEFT JOIN e2x.Lookups AS lookupCountryOfIncorporationEstablishment4 ON lookupCountryOfIncorporationEstablishment4.LookupName = 'Country' AND lookupCountryOfIncorporationEstablishment4.EId = lec.[CountryOfIncorporationId]
    LEFT JOIN e2x.Lookups AS lookupCountryOfDomicile5 ON lookupCountryOfDomicile5.LookupName = 'Country' AND lookupCountryOfDomicile5.EId = le.[NationalCountryId]
    LEFT JOIN e2x.Lookups AS lookupMoneyServicesBusiness6 ON lookupMoneyServicesBusiness6.LookupName = 'YesNo' AND lookupMoneyServicesBusiness6.EId = lec.[IsMoneyServicesBusiness]
    LEFT JOIN e2x.Lookups AS lookupIsTheEntityRegulated7 ON lookupIsTheEntityRegulated7.LookupName = 'YesNo' AND lookupIsTheEntityRegulated7.EId = lec.[IsRegulated]
    LEFT JOIN e2x.Lookups AS lookupIsTheEntityAWhollyOwnedSubsidiaryOfAParent8 ON lookupIsTheEntityAWhollyOwnedSubsidiaryOfAParent8.LookupName = 'YesNo' AND lookupIsTheEntityAWhollyOwnedSubsidiaryOfAParent8.EId = lec.[IsWhollyOwnedByParent]
    LEFT JOIN e2x.Lookups AS lookupParentCompanyCountryOfIncorporation9 ON lookupParentCompanyCountryOfIncorporation9.LookupName = 'Country' AND lookupParentCompanyCountryOfIncorporation9.EId = lec.[ParentCompanyCOI]
    LEFT JOIN e2x.Lookups AS lookupIsTheParentEntityRegulated10 ON lookupIsTheParentEntityRegulated10.LookupName = 'YesNo' AND lookupIsTheParentEntityRegulated10.EId = lec.[IsParentRegulated]
    LEFT JOIN e2x.Lookups AS lookupParentRegulatedBy11 ON lookupParentRegulatedBy11.LookupName = 'LookupRegulator' AND lookupParentRegulatedBy11.EId = lec.[ParentRegulatedBy]
    LEFT JOIN e2x.Lookups AS lookupParentSAmlGuidelinesReviewedAndApproved12 ON lookupParentSAmlGuidelinesReviewedAndApproved12.LookupName = 'YesNo' AND lookupParentSAmlGuidelinesReviewedAndApproved12.EId = lec.[IsGuidelinesApproved]
    LEFT JOIN e2x.Lookups AS lookupCanTheCorporationIssueBearerShares13 ON lookupCanTheCorporationIssueBearerShares13.LookupName = 'YesNo' AND lookupCanTheCorporationIssueBearerShares13.EId = lec.[CanIssueBearerShares]
    LEFT JOIN e2x.Lookups AS lookupIsTheAdministratorRegulated14 ON lookupIsTheAdministratorRegulated14.LookupName = 'YesNo' AND lookupIsTheAdministratorRegulated14.EId = lec.[IsAdministratorRegulated]
    LEFT JOIN e2x.Lookups AS lookupIsTheInvestmentAdviserRegulated15 ON lookupIsTheInvestmentAdviserRegulated15.LookupName = 'YesNo' AND lookupIsTheInvestmentAdviserRegulated15.EId = lec.[IsAdviserRegulated]
    LEFT JOIN e2x.Lookups AS lookupIsTheInvestmentManagerRegulated16 ON lookupIsTheInvestmentManagerRegulated16.LookupName = 'YesNo' AND lookupIsTheInvestmentManagerRegulated16.EId = lec.[IsManagerRegulated]
    LEFT JOIN e2x.Lookups AS lookupIsThereAnAmlProgramInPlace17 ON lookupIsThereAnAmlProgramInPlace17.LookupName = 'YesNo' AND lookupIsThereAnAmlProgramInPlace17.EId = lec.[IsThereAMLApproved]
    LEFT JOIN e2x.Lookups AS lookupPrincipalPlaceOfBusiness18 ON lookupPrincipalPlaceOfBusiness18.LookupName = 'Country' AND lookupPrincipalPlaceOfBusiness18.EId = lec.[PrincipalPlaceBusinessId]
    LEFT JOIN e2x.Lookups AS lookupTypeOfInvestor19 ON lookupTypeOfInvestor19.LookupName = 'TypeOfInvestor' AND lookupTypeOfInvestor19.EId = lex.[TypeOfInvestorId]
    LEFT JOIN e2x.Lookups AS lookupApplicableVeryHighRiskIndustry20 ON lookupApplicableVeryHighRiskIndustry20.LookupName = 'AppVHighRiskIndustry' AND lookupApplicableVeryHighRiskIndustry20.EId = lex.[ApplicableVeryHighRiskIndustryId]
    LEFT JOIN e2x.Lookups AS lookupEnterpriseSic21 ON lookupEnterpriseSic21.LookupName = 'SicCodeDescription' AND lookupEnterpriseSic21.EId = lec.[LookupSicCodeId]
    LEFT JOIN e2x.Lookups AS lookupApplicableEntityType22 ON lookupApplicableEntityType22.LookupName = 'RiskEntityType' AND lookupApplicableEntityType22.EId = lex.[ApplicableEntityTypeId]
    LEFT JOIN e2x.Lookups AS lookupPepControlledEntity23 ON lookupPepControlledEntity23.LookupName = 'YesNo' AND lookupPepControlledEntity23.EId = lex.[PEPControlledEntityId]
    LEFT JOIN e2x.Lookups AS lookupMaterialNegativeNews24 ON lookupMaterialNegativeNews24.LookupName = 'YesNo' AND lookupMaterialNegativeNews24.EId = lex.[MaterialNegativeNewsId]
    LEFT JOIN e2x.Lookups AS lookupIsThisACustomerOfConcern25 ON lookupIsThisACustomerOfConcern25.LookupName = 'YesNo' AND lookupIsThisACustomerOfConcern25.EId = lex.[IsthisCustomerConcernId]
    LEFT JOIN e2x.Lookups AS lookupSpecializedEddRequired26 ON lookupSpecializedEddRequired26.LookupName = 'YesNo' AND lookupSpecializedEddRequired26.EId = lex.[SpecEDDRequiredId]
    LEFT JOIN e2x.Lookups AS lookupKycLevel27 ON lookupKycLevel27.LookupName = 'LookupKYCLevel' AND lookupKycLevel27.EId = le.[KYCLevelId]
    LEFT JOIN e2x.Lookups AS lookupEntityType28 ON lookupEntityType28.LookupName = 'EntityType' AND lookupEntityType28.EId = lec.[EntityType]
    LEFT JOIN e2x.Lookups AS lookupPreviousName29 ON lookupPreviousName29.LookupName = 'YesNo' AND lookupPreviousName29.EId = lek.[EntityHavePreviousNameId]
    LEFT JOIN e2x.Lookups AS lookupLegalStatus30 ON lookupLegalStatus30.LookupName = 'LookupLegalStatus' AND lookupLegalStatus30.EId = lec.[LegalStatusId]
    LEFT JOIN e2x.Lookups AS lookupKycClientType31 ON lookupKycClientType31.LookupName = 'KYCClientType' AND lookupKycClientType31.EId = le.[ClientType]
    LEFT JOIN e2x.Lookups AS lookupAdministratorRegulatedBy32 ON lookupAdministratorRegulatedBy32.LookupName = 'LookupRegulator' AND lookupAdministratorRegulatedBy32.EId = lec.[AdministratorRegulatedBy]
    LEFT JOIN e2x.Lookups AS lookupInvestmentAdviserRegulatedBy33 ON lookupInvestmentAdviserRegulatedBy33.LookupName = 'LookupRegulator' AND lookupInvestmentAdviserRegulatedBy33.EId = lec.[AdviserRegulatedBy]
    LEFT JOIN e2x.Lookups AS lookupInvestmentManagerRegulatedBy34 ON lookupInvestmentManagerRegulatedBy34.LookupName = 'LookupRegulator' AND lookupInvestmentManagerRegulatedBy34.EId = lec.[ManagerRegulatedBy]
    LEFT JOIN e2x.Lookups AS lookupThirdPartyAccount35 ON lookupThirdPartyAccount35.LookupName = 'YesNoNotApplicable' AND lookupThirdPartyAccount35.EId = lex.[ThirdPartyAccount]
    LEFT JOIN e2x.Lookups AS lookupPrimaryBusinessLocation36 ON lookupPrimaryBusinessLocation36.LookupName = 'Country' AND lookupPrimaryBusinessLocation36.EId = lec.[PrimaryBusinessLocationId]
    LEFT JOIN e2x.Lookups AS lookupLocationOfBusinessActivity37 ON lookupLocationOfBusinessActivity37.LookupName = 'Country' AND lookupLocationOfBusinessActivity37.EId = lec.[LocationBusinessActivity]
    LEFT JOIN e2x.Lookups AS lookupIsItConsideredACorporation38 ON lookupIsItConsideredACorporation38.LookupName = 'YesNoNotApplicable' AND lookupIsItConsideredACorporation38.EId = lecex.[IsCorporation]
    LEFT JOIN e2x.Lookups AS lookupPartnershipsCustodianHasAssumedWithholding39 ON lookupPartnershipsCustodianHasAssumedWithholding39.LookupName = 'YesNoNotApplicable' AND lookupPartnershipsCustodianHasAssumedWithholding39.EId = lecex.[PartCustodianUSSI]
    LEFT JOIN e2x.Lookups AS lookupElectedToBeTreatedAsACorporationUnderUSTaxLaw40 ON lookupElectedToBeTreatedAsACorporationUnderUSTaxLaw40.LookupName = 'YesNoNotApplicable' AND lookupElectedToBeTreatedAsACorporationUnderUSTaxLaw40.EId = lecex.[ElectedCorporationUSTL]
    LEFT JOIN e2x.Lookups AS lookupConsideredAsAWithholdingForeignPartnershipUnderUSTaxLaw41 ON lookupConsideredAsAWithholdingForeignPartnershipUnderUSTaxLaw41.LookupName = 'YesNoNotApplicable' AND lookupConsideredAsAWithholdingForeignPartnershipUnderUSTaxLaw41.EId = lecex.[ConsWithholdForeignPartUSTL]
    LEFT JOIN e2x.Lookups AS lookupHas25OrFewerPartnersAndIsConsideredAsAPartnershipUnderUSTaxLaw42 ON lookupHas25OrFewerPartnersAndIsConsideredAsAPartnershipUnderUSTaxLaw42.LookupName = 'YesNoNotApplicable' AND lookupHas25OrFewerPartnersAndIsConsideredAsAPartnershipUnderUSTaxLaw42.EId = lecex.[Less25PartnersConsPartnershipUSTL]
    LEFT JOIN e2x.Lookups AS lookupContainsNonCanadianPartners43 ON lookupContainsNonCanadianPartners43.LookupName = 'YesNoNotApplicable' AND lookupContainsNonCanadianPartners43.EId = lecex.[ContNonCanadPartners]
    LEFT JOIN e2x.Lookups AS lookupComplexTrustUnderUSTaxLaw44 ON lookupComplexTrustUnderUSTaxLaw44.LookupName = 'YesNoNotApplicable' AND lookupComplexTrustUnderUSTaxLaw44.EId = lecex.[ComplexTrustUnderUSTL]
    LEFT JOIN e2x.Lookups AS lookupTheAuthorizedTrusteeIsACanadianRegistrantFinancialInstitution45 ON lookupTheAuthorizedTrusteeIsACanadianRegistrantFinancialInstitution45.LookupName = 'YesNoNotApplicable' AND lookupTheAuthorizedTrusteeIsACanadianRegistrantFinancialInstitution45.EId = lecex.[AuthTrusteeIsCanRegistrant]
    LEFT JOIN e2x.Lookups AS lookupTrustIsRegisteredWithIrsAsAWithholdingForeignTrust46 ON lookupTrustIsRegisteredWithIrsAsAWithholdingForeignTrust46.LookupName = 'YesNo' AND lookupTrustIsRegisteredWithIrsAsAWithholdingForeignTrust46.EId = lecex.[TrustRegIRSAsWFT]
    LEFT JOIN e2x.Lookups AS lookupTrustOrDesignatedCustodianHaveAssumedWithholding47 ON lookupTrustOrDesignatedCustodianHaveAssumedWithholding47.LookupName = 'YesNoNotApplicable' AND lookupTrustOrDesignatedCustodianHaveAssumedWithholding47.EId = lecex.[TrustAssumedWithholdingUSSI]
    LEFT JOIN e2x.Lookups AS lookupIsTheTrustCompanyRegisteredForTrustBusiness48 ON lookupIsTheTrustCompanyRegisteredForTrustBusiness48.LookupName = 'YesNo' AND lookupIsTheTrustCompanyRegisteredForTrustBusiness48.EId = lec.[IsTrustCompanyRegistered]
    LEFT JOIN e2x.Lookups AS lookupNationalGovernment49 ON lookupNationalGovernment49.LookupName = 'Country' AND lookupNationalGovernment49.EId = lec.[NationalGovernment]
    LEFT JOIN e2x.Lookups AS lookupDoesTheCharitySolicitDonations50 ON lookupDoesTheCharitySolicitDonations50.LookupName = 'YesNo' AND lookupDoesTheCharitySolicitDonations50.EId = lec.[SolicitsDonations]
    LEFT JOIN e2x.Lookups AS lookupAreContributionsMadeByTheEmployerSettingUpTheScheme51 ON lookupAreContributionsMadeByTheEmployerSettingUpTheScheme51.LookupName = 'YesNo' AND lookupAreContributionsMadeByTheEmployerSettingUpTheScheme51.EId = lex.[NegNewsScreenConducted]
    LEFT JOIN e2x.Lookups AS lookupNace2Code52 ON lookupNace2Code52.LookupName = 'NaceCodeDescription' AND lookupNace2Code52.EId = lec.[Nace]
    LEFT JOIN e2x.Lookups AS lookupNaicsCode53 ON lookupNaicsCode53.LookupName = 'NaicCodeDescription' AND lookupNaicsCode53.EId = lec.[NaicCode]
    LEFT JOIN e2x.Lookups AS lookupIsc54 ON lookupIsc54.LookupName = 'LookupISCCode' AND lookupIsc54.EId = lec.[ISCCode]
    LEFT JOIN e2x.Lookups AS lookupNegativeNewsScreeningConducted55 ON lookupNegativeNewsScreeningConducted55.LookupName = 'YesNo' AND lookupNegativeNewsScreeningConducted55.EId = lex.[NegNewsScreenConducted]
    WHERE le.LegalEntitySubtypeId <> 17
        AND ISNULL(le.IsDeleted, 0) <> 1;
END;
GO