CREATE USER E2X
  IDENTIFIED BY "ergo.1234"
  TEMPORARY TABLESPACE FENERGO_TEMP
  DEFAULT TABLESPACE FENERGO_DATA
  ACCOUNT UNLOCK;

ALTER USER  E2X QUOTA UNLIMITED  ON FENERGO_DATA ;
ALTER USER  E2X QUOTA UNLIMITED  ON FENERGO_INDEX;

GRANT CREATE SESSION,Create table, create view, create procedure, create type, create sequence, create trigger, CREATE MATERIALIZED VIEW  TO  E2X;

DECLARE
  not_exist_grant_option EXCEPTION;
  not_validated_object EXCEPTION;
  invalid_object EXCEPTION;
  v_tableName NVARCHAR2(32767) := '';
  v_error NVARCHAR2(32767) := '';
  PRAGMA EXCEPTION_INIT(not_exist_grant_option, -1720);
  PRAGMA EXCEPTION_INIT(not_validated_object, -4023);
  PRAGMA EXCEPTION_INIT(invalid_object, -40362);
begin
FOR x IN (    SELECT owner, 
						  object_name,
						  DECODE(object_type,   'TABLE',    'select, insert, update, delete',
												'SEQUENCE', 'select',
												'VIEW',     'select', 'execute'					) AS privs,
						  'E2X' AS app_user,
              object_type AS object_type
					 FROM all_objects
					WHERE object_type IN ('TABLE','PACKAGE', 'PROCEDURE','FUNCTION', 'SEQUENCE', 'VIEW')
					  AND owner       IN (SELECT userName FROM dbo.fenergoUsers)
            ORDER BY object_type, owner, object_name  ASC)
LOOP
		BEGIN
			EXECUTE IMMEDIATE 'GRANT ' || x.privs || ' on ' || x.owner || '."' || x.object_name || '" to E2X';
			IF (x.object_type IN ('TABLE','VIEW','FUNCTION')) THEN
					BEGIN
						EXECUTE IMMEDIATE 'GRANT ' || x.privs || ' ON ' || x.owner || '."' || x.object_name || '" TO E2X' ;
					EXCEPTION WHEN OTHERS THEN
						DBMS_OUTPUT.PUT_LINE(DBMS_UTILITY.format_error_stack ());
						DBMS_OUTPUT.PUT_LINE('An error occured grating privileges: '||  'GRANT ' || x.privs || ' ON ' || x.owner || '."' || x.object_name || '" TO E2X');
					END;
			END IF;
		EXCEPTION 
			WHEN not_exist_grant_option THEN
				DBMS_OUTPUT.PUT_LINE('Skipping not exist grant option: ' || x.owner || '."' || x.object_name ) ;
			WHEN not_validated_object THEN
				DBMS_OUTPUT.PUT_LINE('Skipping not validated object: ' || x.owner || '."' || x.object_name ) ;
			WHEN invalid_object THEN
				DBMS_OUTPUT.PUT_LINE('Skipping invalid object: ' || x.owner || '."' || x.object_name ) ;	
			WHEN OTHERS THEN
				DBMS_OUTPUT.PUT_LINE(DBMS_UTILITY.format_error_stack ());
				DBMS_OUTPUT.PUT_LINE('An error occured grating privileges: '||  ' GRANT ' || x.privs || ' ON ' || x.owner || '."' || x.object_name || '" TO ' || x.app_user);
		END; 
   END LOOP;
END;

CREATE TABLE e2x.ExtractConfig
(
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  XTableName varchar2(100) NULL,
  DBViewName varchar2(250) NULL,
  EBusinessEntityId number NULL,
  LEIdColumn varchar2(150) NULL,
  ReturnOneRow NUMBER(1,0) NULL,
  PostDataExtractStrategy nvarchar2(250) NULL,
  MigrationTypeName nvarchar2(100) NULL,
  CustomExecutionStrategy nvarchar2(100) NULL,
  AssociationSourceLEIdColumn nvarchar2(150) NULL
  CONSTRAINT PKExtractConfig PRIMARY KEY (Id)
);

CREATE TABLE E2X.LEDocDownloading
(
  Id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  FenELegalEntityId NUMBER(10,0)  NOT NULL,  
  CONSTRAINT PKDocDownloading PRIMARY KEY (Id)
);

CREATE TABLE E2X.DOCEXPORTFILE
(
  Id NUMBER(10,0)  GENERATED ALWAYS AS IDENTITY,
  CreatedDate timestamp(6),
  EntityId NVARCHAR2 (1000),
  FileName NVARCHAR2 (1000),
  JourneyId NVARCHAR2(1000),
  DocumentType NVARCHAR2(1000),
  FriendlyName NVARCHAR2(1000),
  Properties NVARCHAR2 (1000),
  FenXDocID NVARCHAR2 (1000),  
  MigrationStatus NVARCHAR2 (1000),
  MigrationErrorDetails NVARCHAR2 (1000),
  FenEDocumentId NUMBER(10,0),
  FenEEntityId NUMBER(10,0),
  FenEEntityTypeName NVARCHAR2 (1000),
  CONSTRAINT PKDOCEXPORTFILE PRIMARY KEY (Id)
);

CREATE TABLE E2X.DOCPROCESSINGRESULT
(
  Id NUMBER(10,0)  GENERATED ALWAYS AS IDENTITY,
  FenELegalEntityId NUMBER(10,0),
  FenEDocumentId NUMBER(10,0),
  Processed NUMBER(1,0),
  DocumentDownloaded NUMBER(1,0),
  CONSTRAINT PKDOCPROCESSINGRESULT PRIMARY KEY (Id)
);

CREATE TABLE E2X.Batch
(
  Id NUMBER GENERATED ALWAYS AS IDENTITY,
  Description NVARCHAR2(500),
  CreatedDate TIMESTAMP(6),
  Name NVARCHAR2(50),
  CONSTRAINT PKBatch1 PRIMARY KEY (Id)
);

CREATE TABLE E2X.EntitiesInScope
(
  Id NUMBER GENERATED ALWAYS AS IDENTITY,
  BatchId NUMBER(10,0),
  LEId NUMBER(10,0),
  XEntityId NUMBER(10,0),
  CONSTRAINT PK_E2X_EntitiesInScope PRIMARY KEY (Id)
);

CREATE TABLE E2X.Error
(
  Id NUMBER GENERATED ALWAYS AS IDENTITY,
  ExtractId NUMBER(10,0),
  Domain NVARCHAR2(50),
  AlternativeId NVARCHAR2(50),
  ParentAlternativeId NVARCHAR2(50),
  FenXId NVARCHAR2(50),
  ErrorMessage NVARCHAR2(300),
  LastUpdateDate TIMESTAMP(6),
  CONSTRAINT PKError PRIMARY KEY (Id)
);

CREATE TABLE E2X.Extract
(
  Id NUMBER GENERATED ALWAYS AS IDENTITY,
  CreatedDate TIMESTAMP(6),
  LastUpdateDate TIMESTAMP(6),
  BatchId NUMBER(10,0),
  XMigrationId NUMBER(10,0),
  CONSTRAINT PKExtract PRIMARY KEY (Id)
);

CREATE TABLE E2X.Recon
(
  Id NUMBER GENERATED ALWAYS AS IDENTITY,
  ExtractId NUMBER(10,0),
  Domain NVARCHAR2(350),
  EBusinessentityId NUMBER(10,0),
  EId NUMBER(10,0),
  FenXId NVARCHAR2(50),
  Status NVARCHAR2(50),
  LastUpdateDate TIMESTAMP(6),
  AlternateId NVARCHAR2 (1000),
  CONSTRAINT FK_Recon_Extract PRIMARY KEY (Id)
);

CREATE  TABLE  E2X.IDLIST  
(
     Id INTEGER
    ,BatchId INTEGER
    ,CONSTRAINT PK_IDLIST PRIMARY KEY (Id)

);

CREATE OR REPLACE View E2X.linkedDocument AS
	(
		SELECT 
			Id AS "DocumentLinkId", 
			DocumentId, 
			EntityId AS LEID, 
			IsActive, 
			ParentBusinessEntityId
        FROM dbo.LinkDocumentEntity WHERE IsActive = 1
    );

CREATE OR REPLACE VIEW E2X.vwActiveDocumentLinks AS
SELECT
    Id,
    DocumentId,
    EntityId AS ContextId,
    IsActive,
    IsMain,
    BusinessEntityId,
    ParentBusinessEntityId,
    ParentEntityId
FROM dbo.LinkDocumentEntity
WHERE IsActive = 1;

CREATE OR REPLACE FORCE VIEW E2X.VWDOCUMENTS_ALL ("ID", "LEID", "FILENAME", "LOCATION", "DOCUMENTCATEGORY", "DOCUMENTPURPOSE", "DOCUMENTTYPE", "LASTUPDATEDDATE", "ISACTIVE", "DOCUMENTDIRECTION", "DOCUMENTSTATUS", "FENXID") AS 
WITH DocumentData_CTE ("ID", "LEID", "FILENAME", "LOCATION", "DOCUMENTCATEGORY", "DOCUMENTPURPOSE", "DOCUMENTTYPE", "LASTUPDATEDDATE", "ISACTIVE", "DOCUMENTDIRECTION", "DOCUMENTSTATUS")  AS
( 
  SELECT DISTINCT
    doc.Id AS ID,
    CASE
        WHEN adl.BusinessEntityId = 30 THEN adl.ContextId
        ELSE lea.LegalEntityId
    END AS "LEID",
    doc.Name AS "FILENAME", 
    doc.Location,
    documentCategory.Name AS DOCUMENTCATEGORY,
    documentPurpose.Name AS DOCUMENTPURPOSE,
    documentPurpose.Name AS DOCUMENTTYPE, -- Doc Type in FenX = Document Purpose
    doc.LastUpdatedDate,
    CASE
        WHEN doc.LookupDocumentStatusId = 7 THEN '0'
        ELSE '1'
    END AS ISACTIVE,
    'Inbound' AS DOCUMENTDIRECTION,
    documentStatus.Name AS DOCUMENTSTATUS    
  FROM E2X.vwActiveDocumentLinks adl
  INNER JOIN dbo.Document doc ON adl.DocumentId = doc.Id
  INNER JOIN dbo.DocumentCategory documentCategory ON doc.DocumentCategoryId = documentCategory.Id
  INNER JOIN dbo.DocumentPurpose documentPurpose ON doc.DocumentPurposeId = documentPurpose.Id
  INNER JOIN dbo.DocumentType documentType ON doc.DocumentTypeId = documentType.Id
  INNER JOIN dbo.LookupDocumentStatus documentStatus ON doc.LookupDocumentStatusId = documentStatus.Id
  LEFT JOIN dbo.LegalEntityAssociation lea ON adl.BusinessEntityId = 31 AND adl.ContextId = lea.Id
  WHERE doc.DOCUMENTTYPEID = 3
  AND doc.Location IS NOT NULL
)
, ReconData_CTE (FenXId,EId) AS
(
  SELECT DISTINCT
     FenXId
    ,EId
  FROM 
    e2x.Recon WHERE EBUSINESSENTITYID = 30
)
SELECT
    documentData."ID"
    ,documentData."LEID"
    ,documentData."FILENAME"
    ,documentData."LOCATION"
    ,documentData."DOCUMENTCATEGORY"
    ,documentData."DOCUMENTPURPOSE"
    ,documentData."DOCUMENTTYPE"
    ,documentData."LASTUPDATEDDATE"
    ,documentData."ISACTIVE"
    ,documentData."DOCUMENTDIRECTION"
    ,documentData."DOCUMENTSTATUS"
    ,r.FenXId
FROM DocumentData_CTE documentData
INNER JOIN ReconData_CTE r ON documentData.LEID = r.EId
WHERE documentData."LEID" IS NOT NULL;


CREATE OR REPLACE FORCE VIEW E2X.VWDOCUMENTS ("ID", "LEID", "FILENAME", "LOCATION", "DOCUMENTCATEGORY", "DOCUMENTPURPOSE", "DOCUMENTTYPE", "LASTUPDATEDDATE", "ISACTIVE", "DOCUMENTDIRECTION", "DOCUMENTSTATUS", "FENXID") AS 
SELECT DISTINCT
    documentData."ID"
    ,documentData."LEID"
    ,documentData."FILENAME"
    ,documentData."LOCATION"
    ,documentData."DOCUMENTCATEGORY"
    ,documentData."DOCUMENTPURPOSE"
    ,documentData."DOCUMENTTYPE"
    ,documentData."LASTUPDATEDDATE"
    ,documentData."ISACTIVE"
    ,documentData."DOCUMENTDIRECTION"
    ,documentData."DOCUMENTSTATUS"
    ,documentData.FenXId
FROM E2X.VWDOCUMENTS_ALL documentData
INNER JOIN dbo.Document doc ON documentData.Id = doc.Id
INNER JOIN dbo.LookupDocumentStatus documentStatus ON doc.LookupDocumentStatusId = documentStatus.Id
LEFT JOIN E2X.DOCEXPORTFILE DEF ON DEF.FENEDOCUMENTID = doc.Id 
WHERE documentstatus.Id NOT IN (3,11502) AND DEF.ID IS NULL;

CREATE OR REPLACE FORCE VIEW E2X.VWDOCUMENTS_DELETED ("ID", "LEID", "FILENAME", "LOCATION", "DOCUMENTCATEGORY", "DOCUMENTPURPOSE", "DOCUMENTTYPE", "LASTUPDATEDDATE", "ISACTIVE", "DOCUMENTDIRECTION", "DOCUMENTSTATUS", "FENXID") AS 
SELECT 
    documentData."ID"
    ,documentData."LEID"
    ,documentData."FILENAME"
    ,documentData."LOCATION"
    ,documentData."DOCUMENTCATEGORY"
    ,documentData."DOCUMENTPURPOSE"
    ,documentData."DOCUMENTTYPE"
    ,documentData."LASTUPDATEDDATE"
    ,documentData."ISACTIVE"
    ,documentData."DOCUMENTDIRECTION"
    ,documentData."DOCUMENTSTATUS"
    ,documentData."FENXDOCID"
FROM
(
    SELECT DISTINCT
        documentData."ID"
        ,documentData."LEID"
        ,documentData."FILENAME"
        ,documentData."LOCATION"
        ,documentData."DOCUMENTCATEGORY"
        ,documentData."DOCUMENTPURPOSE"
        ,documentData."DOCUMENTTYPE"
        ,documentData."LASTUPDATEDDATE"
        ,documentData."ISACTIVE"
        ,documentData."DOCUMENTDIRECTION"
        ,documentData."DOCUMENTSTATUS"
        ,DOCEX."FENXDOCID"
    FROM E2X.VWDOCUMENTS_ALL documentData
    INNER JOIN dbo.Document doc ON documentData.Id = doc.Id
    INNER JOIN dbo.LookupDocumentStatus documentStatus ON doc.LookupDocumentStatusId = documentStatus.Id
    INNER JOIN E2X.DocExportFile DOCEX ON documentData."ID" = DOCEX.FenEDocumentId
    WHERE documentstatus.Id IN (3)
    
    UNION ALL
    SELECT 
        doc.Id AS "ID"
        ,LDE.PARENTENTITYID AS "LEID"
        ,doc.Name AS "FILENAME"
        ,doc.Location AS "LOCATION"
        ,documentCategory.Name AS DOCUMENTCATEGORY
        ,documentPurpose.Name AS DOCUMENTPURPOSE
        ,documentPurpose.Name AS DOCUMENTTYPE
        ,doc.LastUpdatedDate
        ,CASE
            WHEN doc.LookupDocumentStatusId = 7 THEN '0'
            ELSE '1'
        END AS ISACTIVE
        ,'Inbound' AS DOCUMENTDIRECTION
        ,documentStatus.Name AS DOCUMENTSTATUS    
        ,DEF.FENXDOCID
    FROM E2X.DocExportFile DEF
    INNER JOIN dbo.LinkDocumentEntity LDE 
        ON DEF.FENEENTITYID = LDE.PARENTENTITYID AND DEF.FENEDOCUMENTID = LDE.DOCUMENTID AND
        LDE.BUSINESSENTITYID = 30 AND ISACTIVE = 0 AND DEF.MIGRATIONSTATUS = 'Processed' AND FENEENTITYTYPENAME = 'LegalEntity'
    LEFT JOIN dbo.Document doc ON LDE.DocumentId = doc.Id
    LEFT JOIN dbo.DocumentCategory documentCategory ON doc.DocumentCategoryId = documentCategory.Id
    LEFT JOIN dbo.DocumentPurpose documentPurpose ON doc.DocumentPurposeId = documentPurpose.Id
    LEFT JOIN dbo.DocumentType documentType ON doc.DocumentTypeId = documentType.Id
    LEFT JOIN dbo.LookupDocumentStatus documentStatus ON doc.LookupDocumentStatusId = documentStatus.Id
) documentData;


CREATE OR REPLACE FORCE VIEW E2X.VWDOCUMENTS_UPDATED ("ID", "LEID", "FILENAME", "LOCATION", "DOCUMENTCATEGORY", "DOCUMENTPURPOSE", "DOCUMENTTYPE", "LASTUPDATEDDATE", "ISACTIVE", "DOCUMENTDIRECTION", "DOCUMENTSTATUS", "FENXID") AS 
  SELECT DISTINCT
    documentData."ID"
    ,documentData."LEID"
    ,documentData."FILENAME"
    ,documentData."LOCATION"
    ,documentData."DOCUMENTCATEGORY"
    ,documentData."DOCUMENTPURPOSE"
    ,documentData."DOCUMENTTYPE"
    ,documentData."LASTUPDATEDDATE"
    ,documentData."ISACTIVE"
    ,documentData."DOCUMENTDIRECTION"
    ,documentData."DOCUMENTSTATUS"
    ,documentData.FenXId
FROM E2X.VWDOCUMENTS_ALL documentData
INNER JOIN dbo.Document doc ON documentData.Id = doc.Id
INNER JOIN dbo.LookupDocumentStatus documentStatus ON doc.LookupDocumentStatusId = documentStatus.Id
INNER JOIN E2X.DocExportFile docef ON documentdata.id = docef.fenedocumentid and docef.feneentitytypename ='LegalEntity'
WHERE documentstatus.Id NOT IN (3) AND docef.MigrationStatus = 'Processed';

--SPECIFIC FOR PROJECT NEED TO BE UPDATED FOR OTHER PROJECTCREATE OR REPLACE VIEW E2X.VWDOCUMENTEXTENSION 
AS
SELECT
    DISTINCT
    DCU.ID,
    DCU.NAME AS "fileName",
    CASE
        WHEN "CURRENT" = 1 THEN 'Yes'
        ELSE 'No'
        END AS "current",
    DCU.DOCUMENTEXPIRATIONDATE AS "expirationDate",
    DCU.DOCUMENTIDENTIFICATIONNUMBER AS "documentIdentificationNumber",
    DCU.ISSUANCEDATE AS "dateOfIssuance",
    DCU.ISSUANCEPLACE AS "placeOfIssuance",
    DCU.ISSUER AS "issuerOfTheDocument",
    CASE
        WHEN LANGNOTENGLISH = 1 THEN 'Yes'
        ELSE 'No'
        END AS "annotatedIfInALanguageOtherThanEnglish",
    DCU.LASTUPDATEDDATE AS "legacyLastUpdatedDate",
    CASE
        WHEN LEGIBLE = 1 THEN 'Yes'
        ELSE 'No'
        END AS "legible",
    CASE
        WHEN SIGNEDANDINFULL = 1 THEN 'Yes'
        ELSE 'No'
        END AS "signedAndInFullIfApplicable",
    P.NAME AS "documentType",
    DCU.ID AS "legacyDocumentId",
    DCU.LastUpdatedBy AS "legacyLastUpdatedBy"
FROM "DBO"."DOCUMENT" DCU
         LEFT JOIN DBO.DOCUMENTPURPOSE P
                   ON DCU.DOCUMENTPURPOSEID = P.ID;

CREATE TABLE E2X.DOCFORPRODUCTIMPORT
(
  Id NUMBER(10,0)  GENERATED ALWAYS AS IDENTITY,
  INPUTFILENAME NVARCHAR2 (500),
  CreatedDate TIMESTAMP(6),
  FENEENTITYID NUMBER(10,0),
  FENXENTITYID NVARCHAR2 (100),
  FENEPRODUCTID NUMBER(10,0),
  FENXPRODUCTID NVARCHAR2 (100),  
  FENXJOURNEYID NVARCHAR2 (100),
  FENECASEID NUMBER(10,0),
  CONSTRAINT PKDOCUMENTFORPRODUCTIMPORT PRIMARY KEY (Id)  
);

CREATE TABLE E2X.PRODUCTIMPORTTEMP
(
  Id NUMBER(10,0)  GENERATED ALWAYS AS IDENTITY,
  FENEPRODUCTID NUMBER(10,0),
  CONSTRAINT PKPRODUCTIMPORTTEMP PRIMARY KEY (Id)  
);

CREATE OR REPLACE VIEW E2X.DOCUMENTSFORPRODUCTLINK 
AS
SELECT DISTINCT
    VWG.ID AS DocumentId
    ,VWG.mainentityid AS ProductId
FROM DBO.VWENTITYDOCUMENTGRID VWG
INNER JOIN E2X.PRODUCTIMPORTTEMP PT ON 
     PT.feneproductid = VWG.mainentityid
    
WHERE businesscontextid = 140 AND ISMAIN = 1;

CREATE OR REPLACE VIEW E2X.VWDOCUMENTSFORPRODUCTS 
AS
SELECT  DISTINCT
     vwedl.EntityId AS "PRODUCTID"
    ,VWEDL.Id AS "DOCUMENTID"
	,VWEDL."NAME" AS "FILENAME"
	,vwedl.location AS "LOCATION"
	,VWEDL.DOCUMENTCATEGORYNAME AS "DOCUMENTCATEGORY"
	,vwedl.documentpurposename AS "DOCUMENTPURPOSE"
	,vwedl.documentpurposename AS "DOCUMENTTYPE"
FROM 
	dbo.vwEntityDocumentGrid  VWEDL  
INNER JOIN E2X.DOCUMENTSFORPRODUCTLINK DFPL
    ON VWEDL.Id = DFPL.DocumentId
LEFT JOIN E2X.DOCEXPORTFILE DEF ON DEF.FENEDOCUMENTID = VWEDL.Id AND DEF.FENEENTITYTYPENAME = 'Product'
WHERE businesscontextid = 140 
AND documentstatusid NOT IN (3,11502)   -- 3 = Rejected, 11502 = Error Uploading
AND ISMAIN = 1 AND vwedl.location IS NOT NULL
AND DEF.ID IS NULL;

CREATE OR REPLACE VIEW E2X.VWDOCUMENTSTOPROCESS AS
SELECT documents.* FROM E2X.LEDOCDOWNLOADING LEC
INNER JOIN E2X.VwDocuments documents ON documents.LEID = LEC.FENELEGALENTITYID;

CREATE OR REPLACE VIEW E2X.VwDocumentsToRemigrate AS
SELECT documents.* FROM E2X.DocExportFile DEF
INNER JOIN E2X.VwDocuments documents ON documents.Id = DEF.FeneDocumentId
WHERE DEF.MigrationStatus = 'NotProcessed';

CREATE OR REPLACE VIEW E2X.VWPRODUCTRECON
AS SELECT 
    ExtractId as "EXTRACTID"
    ,EID as "FENEPRODUCTID"
    ,FenXId as "FENXPRODUCTID"
FROM E2X.Recon WHERE EBusinessEntityId = 140 AND Status = 'Accepted';

CREATE INDEX IDX_LEDocDownloading_FenELegalEntityId ON E2X.LEDocDownloading (FenELegalEntityId);

CREATE INDEX E2X.IDX_EID_RECON ON E2X.RECON (EID);

CREATE INDEX E2X.IDX_FENEDOCID_RECON ON E2X.Docexportfile (FENEDOCUMENTID);

CREATE INDEX E2X.IDX_ENTID_RECON ON E2X.Docexportfile (FENEENTITYID);

CREATE INDEX E2X.IDX_IDLIST_BatchId ON E2X.IDLIST (BatchId);

CREATE TABLE E2X.MIGRATIONSTATUS
(
    Id INT GENERATED ALWAYS AS IDENTITY,
    MigrationId NVARCHAR2(36),
    MigrationDate TIMESTAMP NULL,
    MigrationStatus NVARCHAR2(50) NULL,
    MigratedEntityCount INT NULL,
    MigratedProductCount INT NULL,
    MigratedAssociationCount INT NULL,
    ExtractPath NVARCHAR2(1000) NULL, 
    JurisdictionEvaluationId NVARCHAR2(36) NULL,
    JurisdictionEvaluationStatus NVARCHAR2(50) NULL,
    AccessLayerId NVARCHAR2(36) NULL,
    AccessLayerStatus NVARCHAR2(50) NULL,
    CONSTRAINT PK_MigrationStatus_Id PRIMARY KEY (Id)
)

CREATE OR REPLACE VIEW E2X.VWMIGRATIONSTATUS
AS
SELECT 
    ID,
    MIGRATIONID,
    MIGRATIONDATE, 
    MIGRATIONSTATUS, 
    MIGRATEDENTITYCOUNT,
    MIGRATEDPRODUCTCOUNT,
    MIGRATEDASSOCIATIONCOUNT,
    EXTRACTPATH, 
    JURISDICTIONEVALUATIONID, 
    JURISDICTIONEVALUATIONSTATUS, 
    ACCESSLAYERID, 
    ACCESSLAYERSTATUS
FROM E2X.MIGRATIONSTATUS;

GRANT ALL PRIVILEGES TO SA;
GRANT ALL PRIVILEGES TO E2X;