CREATE OR ALTER VIEW e2x.vwExtractLegalEntityIndividuals
AS
SELECT
    stag.LegalEntityId AS fenEId,
    stag.AlternateId,
    stag.IsCustomer,
    stag.FirstName AS firstName,
    stag.LastName AS lastName,
    CONVERT(CHAR(10), TRY_CONVERT(DATE, stag.DOB), 23) AS dateOfBirth,
    stag.FenENationalCountryId,
    stag.FenENationalCountry AS FenENationalCountry,
    stag.FenXNationalCountry AS nationality,
    stag.FenECitizenshipId,
    stag.FenECitizenship AS FenECitizenship,
    stag.FenXCitizenship AS citizenship,
    stag.FenENaicsId,
    stag.FenENaics AS FenENaics,
    stag.FenXNaics AS [naics],
    stag.FenEPlaceOfBirthId,
    stag.FenEPlaceOfBirth AS FenEPlaceOfBirth,
    stag.FenXPlaceOfBirth AS [placeOfBirth],
    stag.FenELegalEntityTypeId,
    stag.FenELegalEntityType AS FenELegalEntityType,
    stag.FenXLegalEntityType AS [legalEntityType],
    stag.FenETypeOfInvestorId,
    stag.FenETypeOfInvestor AS FenETypeOfInvestor,
    stag.FenXTypeOfInvestor AS [typeOfInvestor],
    stag.FenESpecializedEddRequiredId,
    stag.FenESpecializedEddRequired AS FenESpecializedEddRequired,
    stag.FenXSpecializedEddRequired AS [specializedEddRequired],
    stag.FenESpecializedEddEntityTypeIds,
    stag.FenESpecializedEddEntityType AS FenESpecializedEddEntityType,
    stag.FenXSpecializedEddEntityType AS [specializedEddEntityType],
    stag.FenEKycLevelId,
    stag.FenEKycLevel AS FenEKycLevel,
    stag.FenXKycLevel AS [kycLevel],
    stag.[KycLevelOverrideComment] AS [kycLevelOverrideComment],
    stag.[RegistrationNumber] AS [registrationNumber],
    stag.[AnticipatedActivityOfAccount] AS [anticipatedActivityOfAccount],
    stag.FenERemediationStatusId,
    stag.FenERemediationStatus AS FenERemediationStatus,
    stag.FenXRemediationStatus AS [remediationStatus],
    stag.FenETitleId,
    stag.FenETitle AS FenETitle,
    stag.FenXTitle AS [title],
    stag.FenEInsiderStatusIds,
    stag.FenEInsiderStatus AS FenEInsiderStatus,
    stag.FenXInsiderStatus AS [insiderStatus],
    stag.[CompanyNameInsiderOrShareholderOf] AS [companyNameInsiderOrShareholderOf],
    stag.[Occupation] AS [occupation],
    stag.FenEGenderId,
    stag.FenEGender AS FenEGender,
    stag.FenXGender AS [gender],
    stag.[NumberOfIdentificationDocument] AS [numberOfIdentificationDocument],
    stag.FenEEmploymentStatusId,
    stag.FenEEmploymentStatus AS FenEEmploymentStatus,
    stag.FenXEmploymentStatus AS [employmentStatus],
    stag.[NameOfEmployer] AS [nameOfEmployer],
    stag.[NatureOfSelfEmployment] AS [natureOfSelfEmployment],
    stag.[NationalIdentificationNumber] AS [nationalIdentificationNumber],
    stag.[NetWorthOfTheIndividual] AS [netWorthOfTheIndividual],
    stag.[LengthOfRelationshipWithScotiabank] AS [lengthOfRelationshipWithScotiabank],
    stag.FenENegativeNewsScreeningConductedId,
    stag.FenENegativeNewsScreeningConducted AS FenENegativeNewsScreeningConducted,
    stag.FenXNegativeNewsScreeningConducted AS [negativeNewsScreeningConducted],
    stag.[SummaryOfBusinessActivitiesWithScotia] AS [summaryOfBusinessActivitiesWithScotia],
    stag.[PrimaryRevenueGeneratingProductsAndServices] AS [primaryRevenueGeneratingProductsAndServices],
    stag.[NationalInsuranceNumber] AS [nationalInsuranceNumber],
    stag.[DirectorsIdentificationNumber] AS [directorsIdentificationNumber],
    stag.FenEPepSanctionsId,
    stag.FenEPepSanctions AS FenEPepSanctions,
    stag.FenXPepSanctions AS [pep/Sanctions],
    stag.[MarketingInfo] AS [marketingInfo],
    stag.[LastUpdatedBy] AS [lastUpdatedBy],
    stag.LoadTimestamp
FROM e2x.StagingLegalEntityIndividuals AS stag;
GO
