CREATE TABLE e2x.StagingClassifications
(
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_E2X_StagingClassifications PRIMARY KEY,
    LegalEntityId INT NOT NULL,
    AlternateId VARCHAR(50) NOT NULL,
    LoadTimestamp DATETIME NOT NULL,
    FenELegalEntityCategoryId INT,
    FenELegalEntityCategory NVARCHAR(500) NULL,
    FenXLegalEntityCategory NVARCHAR(500) NULL,
    --DGSD
    FenEDGSDLegalEntityTypeId INT NULL,
    FenEDGSDLegalEntityType NVARCHAR(500) NULL,
    FenXDGSDLegalEntityType NVARCHAR(500) NULL,
    FenEUnderlyingCompanyId INT NULL,
    FenEUnderlyingCompany NVARCHAR(500) NULL,
    FenXUnderlyingCompany NVARCHAR(500) NULL,
    FenEBudgetId INT NULL,
    FenEBudget NVARCHAR(500) NULL,
    FenXBudget NVARCHAR(500) NULL,
    FenENumberOfEmployeesId INT NULL,
    FenENumberOfEmployees NVARCHAR(500) NULL,
    FenXNumberOfEmployees NVARCHAR(500) NULL,
    FenEAnnualTurnOverId INT NULL,
    FenEAnnualTurnOver NVARCHAR(500) NULL,
    FenXAnnualTurnOver NVARCHAR(500) NULL,
    FenEAnnualBalanceSheetId INT NULL,
    FenEAnnualBalanceSheet NVARCHAR(500) NULL,
    FenXAnnualBalanceSheet NVARCHAR(500) NULL,
    FenEFinalDGSDLegalEntityTypeId INT NULL,
    FenEFinalDGSDLegalEntityType NVARCHAR(500) NULL,
    FenXFinalDGSDLegalEntityType NVARCHAR(500) NULL,
    FenECounterPartyEligibilityId INT NULL,
    FenECounterPartyEligibility NVARCHAR(500) NULL,
    FenXCounterPartyEligibility NVARCHAR(500) NULL,
    --Finra
    FenESuitabilityCertificateProvidedId INT NULL,
    FenESuitabilityCertificateProvided NVARCHAR(500) NULL,
    FenXSuitabilityCertificateProvided NVARCHAR(500) NULL,
    FenESuitabilityCertificateSourceId INT NULL,
    FenESuitabilityCertificateSource NVARCHAR(500) NULL,
    FenXSuitabilityCertificateSource NVARCHAR(500) NULL,
    SuitabilityCertificateComment NVARCHAR(2000) NULL,    
    FenEEntityClassificationId INT NULL,
    FenEEntityClassification NVARCHAR(500) NULL,
    FenXEntityClassification NVARCHAR(500) NULL,
    FenETotalAssetsGt50Id INT NULL,
    FenETotalAssetsGt50 NVARCHAR(500) NULL,
    FenXTotalAssetsGt50 NVARCHAR(500) NULL,
    FenEInvRisksIndependentId INT NULL,
    FenEInvRisksIndependent NVARCHAR(500) NULL,
    FenXInvRisksIndependent NVARCHAR(500) NULL,
    IrrelevantInvFactorsComments NVARCHAR(500) NULL,
    FenEIndependentJudgementId INT NULL,
    FenEIndependentJudgement NVARCHAR(500) NULL,
    FenXIndependentJudgement NVARCHAR(500) NULL,
    FenEDilligencePerformedId INT NULL,
    FenEDilligencePerformed NVARCHAR(500) NULL,
    FenXDilligencePerformed NVARCHAR(500) NULL,
    FenERecommendationsMadeId INT NULL,
    FenERecommendationsMade NVARCHAR(500) NULL,
    FenXRecommendationsMade NVARCHAR(500) NULL,
    FenERecommendationsNotExcessiveId INT NULL,
    FenERecommendationsNotExcessive NVARCHAR(500) NULL,
    FenXRecommendationsNotExcessive NVARCHAR(500) NULL
);

CREATE UNIQUE NONCLUSTERED INDEX IX_E2X_StagingClassifications_AlternateId
    ON e2x.StagingClassifications (AlternateId);

CREATE NONCLUSTERED INDEX IX_E2X_StagingClassifications_LegalEntityId
    ON e2x.StagingClassifications (LegalEntityId);
