CREATE OR ALTER VIEW e2x.vwExtractLegalEntityCompanies
AS
SELECT
    stag.LegalEntityId AS fenEId,
    stag.AlternateId,
    stag.IsCustomer,
    stag.[Name] AS legalEntityName,
    stag.FenESubTypeId,
    stag.FenESubType AS FenESubType,
    stag.FenXSubType AS legalEntityType,
    stag.LEI AS lei,
    stag.FenELegalEntityCategoryId,
    stag.FenELegalEntityCategory AS FenELegalEntityCategory,
    stag.FenXLegalEntityCategory AS [legalEntityCategory],
    stag.FenENaicsId,
    stag.FenENaics AS FenENaics,
    stag.FenXNaics AS [naics],
    stag.FenEIsicId,
    stag.FenEIsic AS FenEIsic,
    stag.FenXIsic AS [isic],
    CONVERT(CHAR(10), TRY_CONVERT(DATE, stag.[DateOfIncorporationEstablishment]), 23) AS [dateOfIncorporationEstablishment],
    stag.FenECountryOfIncorporationEstablishmentId,
    stag.FenECountryOfIncorporationEstablishment AS FenECountryOfIncorporationEstablishment,
    stag.FenXCountryOfIncorporationEstablishment AS [countryOfIncorporation/Establishment],
    stag.FenECountryOfDomicileId,
    stag.FenECountryOfDomicile AS FenECountryOfDomicile,
    stag.FenXCountryOfDomicile AS [countryOfDomicile],
    stag.FenEMoneyServicesBusinessId,
    stag.FenEMoneyServicesBusiness AS FenEMoneyServicesBusiness,
    stag.FenXMoneyServicesBusiness AS [moneyServicesBusiness],
    stag.FenEIsTheEntityRegulatedId,
    stag.FenEIsTheEntityRegulated AS FenEIsTheEntityRegulated,
    stag.FenXIsTheEntityRegulated AS [isTheEntityRegulated],
    stag.FenEIsTheEntityAWhollyOwnedSubsidiaryOfAParentId,
    stag.FenEIsTheEntityAWhollyOwnedSubsidiaryOfAParent AS FenEIsTheEntityAWhollyOwnedSubsidiaryOfAParent,
    stag.FenXIsTheEntityAWhollyOwnedSubsidiaryOfAParent AS [isTheEntityAWholly-OwnedSubsidiaryOfAParent],
    stag.FenEParentCompanyCountryOfIncorporationId,
    stag.FenEParentCompanyCountryOfIncorporation AS FenEParentCompanyCountryOfIncorporation,
    stag.FenXParentCompanyCountryOfIncorporation AS [parentCompanyCountryOfIncorporation],
    stag.FenEIsTheParentEntityRegulatedId,
    stag.FenEIsTheParentEntityRegulated AS FenEIsTheParentEntityRegulated,
    stag.FenXIsTheParentEntityRegulated AS [isTheParentEntityRegulated],
    stag.FenEParentRegulatedById,
    stag.FenEParentRegulatedBy AS FenEParentRegulatedBy,
    stag.FenXParentRegulatedBy AS [parentRegulatedBy],
    stag.FenEParentSAmlGuidelinesReviewedAndApprovedId,
    stag.FenEParentSAmlGuidelinesReviewedAndApproved AS FenEParentSAmlGuidelinesReviewedAndApproved,
    stag.FenXParentSAmlGuidelinesReviewedAndApproved AS [parent'sAmlGuidelinesReviewedAndApproved],
    stag.FenENameOfExchangesTheParentEntityIsListedOnIds,
    stag.FenENameOfExchangesTheParentEntityIsListedOn AS FenENameOfExchangesTheParentEntityIsListedOn,
    stag.FenXNameOfExchangesTheParentEntityIsListedOn AS [nameOfExchangesTheParentEntityIsListedOn],
    stag.FenECanTheCorporationIssueBearerSharesId,
    stag.FenECanTheCorporationIssueBearerShares AS FenECanTheCorporationIssueBearerShares,
    stag.FenXCanTheCorporationIssueBearerShares AS [canTheCorporationIssueBearerShares],
    stag.FenEIsTheAdministratorRegulatedId,
    stag.FenEIsTheAdministratorRegulated AS FenEIsTheAdministratorRegulated,
    stag.FenXIsTheAdministratorRegulated AS [isTheAdministratorRegulated],
    stag.FenEIsTheInvestmentAdviserRegulatedId,
    stag.FenEIsTheInvestmentAdviserRegulated AS FenEIsTheInvestmentAdviserRegulated,
    stag.FenXIsTheInvestmentAdviserRegulated AS [isTheInvestmentAdviserRegulated],
    stag.FenEIsTheInvestmentManagerRegulatedId,
    stag.FenEIsTheInvestmentManagerRegulated AS FenEIsTheInvestmentManagerRegulated,
    stag.FenXIsTheInvestmentManagerRegulated AS [isTheInvestmentManagerRegulated?],
    stag.FenERegulatedByIds,
    stag.FenERegulatedBy AS FenERegulatedBy,
    stag.FenXRegulatedBy AS [regulatedBy],
    stag.[RegulatoryId] AS [regulatoryId],
    stag.FenEIsThereAnAmlProgramInPlaceId,
    stag.FenEIsThereAnAmlProgramInPlace AS FenEIsThereAnAmlProgramInPlace,
    stag.FenXIsThereAnAmlProgramInPlace AS [isThereAnAmlProgramInPlace],
    stag.FenEPrincipalPlaceOfBusinessId,
    stag.FenEPrincipalPlaceOfBusiness AS FenEPrincipalPlaceOfBusiness,
    stag.FenXPrincipalPlaceOfBusiness AS [principalPlaceOfBusiness],
    stag.FenETypeOfInvestorId,
    stag.FenETypeOfInvestor AS FenETypeOfInvestor,
    stag.FenXTypeOfInvestor AS [typeOfInvestor],
    stag.FenEApplicableVeryHighRiskIndustryId,
    stag.FenEApplicableVeryHighRiskIndustry AS FenEApplicableVeryHighRiskIndustry,
    stag.FenXApplicableVeryHighRiskIndustry AS [applicableVeryHighRiskIndustry],
    stag.FenEEnterpriseSicId,
    stag.FenEEnterpriseSic AS FenEEnterpriseSic,
    stag.FenXEnterpriseSic AS [enterpriseSic],
    stag.FenEApplicableEntityTypeId,
    stag.FenEApplicableEntityType AS FenEApplicableEntityType,
    stag.FenXApplicableEntityType AS [applicableEntityType],
    stag.FenEPepControlledEntityId,
    stag.FenEPepControlledEntity AS FenEPepControlledEntity,
    stag.FenXPepControlledEntity AS [pepControlledEntity],
    stag.FenEMaterialNegativeNewsId,
    stag.FenEMaterialNegativeNews AS FenEMaterialNegativeNews,
    stag.FenXMaterialNegativeNews AS [materialNegativeNews],
    stag.FenEIsThisACustomerOfConcernId,
    stag.FenEIsThisACustomerOfConcern AS FenEIsThisACustomerOfConcern,
    stag.FenXIsThisACustomerOfConcern AS [isThisACustomerOfConcern],
    stag.FenEGlobalModelExclusionsIds,
    stag.FenEGlobalModelExclusions AS FenEGlobalModelExclusions,
    stag.FenXGlobalModelExclusions AS [globalModelExclusions],
    stag.FenESpecializedEddRequiredId,
    stag.FenESpecializedEddRequired AS FenESpecializedEddRequired,
    stag.FenXSpecializedEddRequired AS [specializedEddRequired],
    stag.FenESpecializedEddEntityTypeIds,
    stag.FenESpecializedEddEntityType AS FenESpecializedEddEntityType,
    stag.FenXSpecializedEddEntityType AS [specializedEddEntityType],
    stag.[RiskCategory] AS [riskCategory],
    stag.FenEKycLevelId,
    stag.FenEKycLevel AS FenEKycLevel,
    stag.FenXKycLevel AS [kycLevel],
    stag.[KycLevelOverrideComment] AS [kycLevelOverrideComment],
    stag.FenEEntityTypeId,
    stag.FenEEntityType AS FenEEntityType,
    stag.FenXEntityType AS [entityType],
    stag.[RegistrationNumber] AS [registrationNumber],
    stag.[RegistrationBody] AS [registrationBody],
    stag.[OperatingTradingName] AS [operating/tradingName],
    stag.FenEPreviousNameId,
    stag.FenEPreviousName AS FenEPreviousName,
    stag.FenXPreviousName AS [previousName],
    stag.[Website] AS [website],
    CONVERT(CHAR(10), TRY_CONVERT(DATE, stag.[DateOfEstablishment]), 23) AS [dateOfEstablishment],
    CONVERT(CHAR(10), TRY_CONVERT(DATE, stag.[AccountActivityReview]), 23) AS [accountActivityReview],
    stag.[NatureOfActivityBusiness] AS [natureOfActivity/Business],
    stag.[PartnershipType] AS [partnershipType],
    stag.FenELegalStatusId,
    stag.FenELegalStatus AS FenELegalStatus,
    stag.FenXLegalStatus AS [legalStatus],
    stag.[Ltid] AS [ltid],
    stag.FenERegulatoryStatusIds,
    stag.FenERegulatoryStatus AS FenERegulatoryStatus,
    stag.FenXRegulatoryStatus AS [regulatoryStatus],
    stag.FenEApplicableExemptionCategoriesIds,
    stag.FenEApplicableExemptionCategories AS FenEApplicableExemptionCategories,
    stag.FenXApplicableExemptionCategories AS [applicableExemptionCategories],
    stag.FenENameOfExchangesTheEntityIsListedOnIds,
    stag.FenENameOfExchangesTheEntityIsListedOn AS FenENameOfExchangesTheEntityIsListedOn,
    stag.FenXNameOfExchangesTheEntityIsListedOn AS [nameOfExchangesTheEntityIsListedOn],
    stag.FenEKycClientTypeId,
    stag.FenEKycClientType AS FenEKycClientType,
    stag.FenXKycClientType AS [kycClientType],
    stag.FenEAdministratorRegulatedById,
    stag.FenEAdministratorRegulatedBy AS FenEAdministratorRegulatedBy,
    stag.FenXAdministratorRegulatedBy AS [administratorRegulatedBy],
    stag.FenEInvestmentAdviserRegulatedById,
    stag.FenEInvestmentAdviserRegulatedBy AS FenEInvestmentAdviserRegulatedBy,
    stag.FenXInvestmentAdviserRegulatedBy AS [investmentAdviserRegulatedBy],
    stag.FenEInvestmentManagerRegulatedById,
    stag.FenEInvestmentManagerRegulatedBy AS FenEInvestmentManagerRegulatedBy,
    stag.FenXInvestmentManagerRegulatedBy AS [investmentManagerRegulatedBy],
    stag.[AnticipatedActivityOfAccount] AS [anticipatedActivityOfAccount],
    stag.[DoesTheEntityHaveAPreviousNames] AS [doesTheEntityHaveAPreviousNames?],
    CONVERT(CHAR(10), TRY_CONVERT(DATE, stag.[DateOfLastNameChange]), 23) AS [dateOfLastNameChange],
    stag.FenEThirdPartyAccountId,
    stag.FenEThirdPartyAccount AS FenEThirdPartyAccount,
    stag.FenXThirdPartyAccount AS [thirdPartyAccount],
    CONVERT(CHAR(10), TRY_CONVERT(DATE, stag.[DateOfIncorporation]), 23) AS [dateOfIncorporation],
    stag.FenEPrimaryBusinessLocationId,
    stag.FenEPrimaryBusinessLocation AS FenEPrimaryBusinessLocation,
    stag.FenXPrimaryBusinessLocation AS [primaryBusinessLocation],
    stag.FenELocationOfBusinessActivityId,
    stag.FenELocationOfBusinessActivity AS FenELocationOfBusinessActivity,
    stag.FenXLocationOfBusinessActivity AS [locationOfBusiness/Activity],
    stag.FenEIsItConsideredACorporationId,
    stag.FenEIsItConsideredACorporation AS FenEIsItConsideredACorporation,
    stag.FenXIsItConsideredACorporation AS [isItConsideredACorporation],
    stag.FenEPartnershipsCustodianHasAssumedWithholdingId,
    stag.FenEPartnershipsCustodianHasAssumedWithholding AS FenEPartnershipsCustodianHasAssumedWithholding,
    stag.FenXPartnershipsCustodianHasAssumedWithholding AS [partnershipsCustodianHasAssumedWithholding],
    stag.FenEElectedToBeTreatedAsACorporationUnderUSTaxLawId,
    stag.FenEElectedToBeTreatedAsACorporationUnderUSTaxLaw AS FenEElectedToBeTreatedAsACorporationUnderUSTaxLaw,
    stag.FenXElectedToBeTreatedAsACorporationUnderUSTaxLaw AS [electedToBeTreatedAsACorporationUnderUSTaxLaw],
    stag.FenEConsideredAsAWithholdingForeignPartnershipUnderUSTaxLawId,
    stag.FenEConsideredAsAWithholdingForeignPartnershipUnderUSTaxLaw AS FenEConsideredAsAWithholdingForeignPartnershipUnderUSTaxLaw,
    stag.FenXConsideredAsAWithholdingForeignPartnershipUnderUSTaxLaw AS [consideredAsAWithholdingForeignPartnershipUnderUSTaxLaw],
    stag.FenEHas25OrFewerPartnersAndIsConsideredAsAPartnershipUnderUSTaxLawId,
    stag.FenEHas25OrFewerPartnersAndIsConsideredAsAPartnershipUnderUSTaxLaw AS FenEHas25OrFewerPartnersAndIsConsideredAsAPartnershipUnderUSTaxLaw,
    stag.FenXHas25OrFewerPartnersAndIsConsideredAsAPartnershipUnderUSTaxLaw AS [has25OrFewerPartnersAndIsConsideredAsAPartnershipUnderUSTaxLaw],
    stag.FenEContainsNonCanadianPartnersId,
    stag.FenEContainsNonCanadianPartners AS FenEContainsNonCanadianPartners,
    stag.FenXContainsNonCanadianPartners AS [containsNonCanadianPartners],
    stag.FenEComplexTrustUnderUSTaxLawId,
    stag.FenEComplexTrustUnderUSTaxLaw AS FenEComplexTrustUnderUSTaxLaw,
    stag.FenXComplexTrustUnderUSTaxLaw AS [complexTrustUnderUSTaxLaw],
    stag.FenETheAuthorizedTrusteeIsACanadianRegistrantFinancialInstitutionId,
    stag.FenETheAuthorizedTrusteeIsACanadianRegistrantFinancialInstitution AS FenETheAuthorizedTrusteeIsACanadianRegistrantFinancialInstitution,
    stag.FenXTheAuthorizedTrusteeIsACanadianRegistrantFinancialInstitution AS [theAuthorizedTrusteeIsACanadianRegistrant/FinancialInstitution],
    stag.FenETrustIsRegisteredWithIrsAsAWithholdingForeignTrustId,
    stag.FenETrustIsRegisteredWithIrsAsAWithholdingForeignTrust AS FenETrustIsRegisteredWithIrsAsAWithholdingForeignTrust,
    stag.FenXTrustIsRegisteredWithIrsAsAWithholdingForeignTrust AS [trustIsRegisteredWithIrsAsAWithholdingForeignTrust],
    stag.FenETrustOrDesignatedCustodianHaveAssumedWithholdingId,
    stag.FenETrustOrDesignatedCustodianHaveAssumedWithholding AS FenETrustOrDesignatedCustodianHaveAssumedWithholding,
    stag.FenXTrustOrDesignatedCustodianHaveAssumedWithholding AS [trustOrDesignatedCustodianHaveAssumedWithholding],
    stag.FenEIsTheTrustCompanyRegisteredForTrustBusinessId,
    stag.FenEIsTheTrustCompanyRegisteredForTrustBusiness AS FenEIsTheTrustCompanyRegisteredForTrustBusiness,
    stag.FenXIsTheTrustCompanyRegisteredForTrustBusiness AS [isTheTrustCompanyRegisteredForTrustBusiness],
    stag.[RegisteredWith] AS [registeredWith],
    stag.[PrimaryBusinessActivity] AS [primaryBusinessActivity],
    stag.[NatureOfFunding] AS [natureOfFunding],
    stag.[StructureType] AS [structureType],
    stag.FenENationalGovernmentId,
    stag.FenENationalGovernment AS FenENationalGovernment,
    stag.FenXNationalGovernment AS [nationalGovernment],
    stag.[NameOfHomeStateAuthority] AS [nameOfHomeStateAuthority],
    stag.FenEDoesTheCharitySolicitDonationsId,
    stag.FenEDoesTheCharitySolicitDonations AS FenEDoesTheCharitySolicitDonations,
    stag.FenXDoesTheCharitySolicitDonations AS [doesTheCharitySolicitDonations],
    stag.[PensionSchemeRegistrationNumber] AS [pensionSchemeRegistrationNumber],
    stag.FenEAreContributionsMadeByTheEmployerSettingUpTheSchemeId,
    stag.FenEAreContributionsMadeByTheEmployerSettingUpTheScheme AS FenEAreContributionsMadeByTheEmployerSettingUpTheScheme,
    stag.FenXAreContributionsMadeByTheEmployerSettingUpTheScheme AS [areContributionsMadeByTheEmployerSettingUpTheScheme],
    stag.[NameOfPensionSchemeAdministrator] AS [nameOfPensionSchemeAdministrator],
    stag.[NameOfPensionSchemePromoter] AS [nameOfPensionSchemePromoter],
    stag.[NameOfPensionSchemeSponsor] AS [nameOfPensionSchemeSponsor],
    stag.FenENace2CodeId,
    stag.FenENace2Code AS FenENace2Code,
    stag.FenXNace2Code AS [nace2Code],
    stag.[StockExchangeCode] AS [stockExchangeCode],
    stag.[CentralIndexKey] AS [centralIndexKey],
    stag.[SwiftBic] AS [swiftBic],
    stag.FenENaicsCodeId,
    stag.FenENaicsCode AS FenENaicsCode,
    stag.FenXNaicsCode AS [naicsCode],
    stag.FenEIscId,
    stag.FenEIsc AS FenEIsc,
    stag.FenXIsc AS [isc],
    stag.[LengthOfRelationshipWithScotiabank] AS [lengthOfRelationshipWithScotiabank],
    stag.FenENegativeNewsScreeningConductedId,
    stag.FenENegativeNewsScreeningConducted AS FenENegativeNewsScreeningConducted,
    stag.FenXNegativeNewsScreeningConducted AS [negativeNewsScreeningConducted],
    stag.[SummaryOfBusinessActivitiesWithScotia] AS [summaryOfBusinessActivitiesWithScotia],
    stag.[AnnualRevenueUsdMillions] AS [annualRevenueUsdMillions],
    stag.[BusinessChangesMadeInTheLast5Years] AS [businessChangesMadeInTheLast5Years],
    stag.[BusinessDescription] AS [businessDescription],
    stag.[NumberOfEmployees] AS [numberOfEmployees],
    stag.[PrimaryCustomerBase] AS [primaryCustomerBase],
    stag.[PrimaryRevenueGeneratingProductsAndServices] AS [primaryRevenueGeneratingProductsAndServices],
    stag.FenESignificantCustomerCountriesIds,
    stag.FenESignificantCustomerCountries AS FenESignificantCustomerCountries,
    stag.FenXSignificantCustomerCountries AS [significantCustomerCountries],
    stag.FenESignificantRevenueCountriesIds,
    stag.FenESignificantRevenueCountries AS FenESignificantRevenueCountries,
    stag.FenXSignificantRevenueCountries AS [significantRevenueCountries],
    stag.FenESignificantSupplierCountriesIds,
    stag.FenESignificantSupplierCountries AS FenESignificantSupplierCountries,
    stag.FenXSignificantSupplierCountries AS [significantSupplierCountries],
    stag.LoadTimestamp
FROM e2x.StagingLegalEntityCompanies AS stag;
GO
