CREATE OR ALTER VIEW e2x.vwExtractProducts
AS
SELECT
    stag.AlternateId,
    stag.ProductId AS fenEId,
    stag.LegalEntityId,
    stag.CaseId,
    stag.FenEProductCategoryId,
    stag.FenEProductCategory AS FenEProductCategory,
    stag.FenXProductCategory AS productCategory,
    stag.FenELookupProductTypeId,
    stag.FenELookupProductType AS FenELookupProductType,
    stag.FenXLookupProductType AS productType,
    stag.FenEProductStatusId,
    stag.FenEProductStatus AS FenEProductStatus,
    stag.FenXProductStatus AS region,
    stag.ParentAlternateId,
    stag.FenEBookingEntityId,
    stag.FenEBookingEntity AS FenEBookingEntity,
    stag.FenXBookingEntity AS [bookingEntity],
    stag.FenEArrangingEntityId,
    stag.FenEArrangingEntity AS FenEArrangingEntity,
    stag.FenXArrangingEntity AS [arrangingEntity],
    stag.FenEInternalDeskId,
    stag.FenEInternalDesk AS FenEInternalDesk,
    stag.FenXInternalDesk AS [internalDesk],
    stag.[IntendedUseOfAccount] AS [intendedUseOfAccount],
    CONVERT(CHAR(10), TRY_CONVERT(DATE, stag.[CreatedDate]), 23) AS [createdDate],
    CONVERT(CHAR(10), TRY_CONVERT(DATE, stag.[ActivatedDate]), 23) AS [activatedDate],
    CONVERT(CHAR(10), TRY_CONVERT(DATE, stag.[LastUpdated]), 23) AS [lastUpdated],
    CONVERT(CHAR(10), TRY_CONVERT(DATE, stag.[KycApprovalDate]), 23) AS [kycApprovalDate],
    stag.[NamesOfSalesPersons] AS [namesOfSalesPersons],
    stag.FenEReasonForProductClosureId,
    stag.FenEReasonForProductClosure AS FenEReasonForProductClosure,
    stag.FenXReasonForProductClosure AS [reasonForProductClosure],
    stag.FenEExpectedActivityTypeId,
    stag.FenEExpectedActivityType AS FenEExpectedActivityType,
    stag.FenXExpectedActivityType AS [expectedActivityType],
    stag.FenEFrequencyOfTradingVolumeId,
    stag.FenEFrequencyOfTradingVolume AS FenEFrequencyOfTradingVolume,
    stag.FenXFrequencyOfTradingVolume AS [frequencyOfTradingVolume],
    stag.FenESourceOfFundsId,
    stag.FenESourceOfFunds AS FenESourceOfFunds,
    stag.FenXSourceOfFunds AS [sourceOfFunds],
    stag.[SourceOfFundsDetails] AS [sourceOfFundsDetails],
    stag.LoadTimestamp
FROM e2x.StagingProducts AS stag;
GO
