CREATE TABLE e2x.StagingLegalEntityIndividuals
(
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_E2X_StagingLegalEntityIndividuals PRIMARY KEY,
    [LegalEntityId] INT NOT NULL,
    [AlternateId] VARCHAR(50) NOT NULL,
    [IsCustomer] BIT NULL,
    [FirstName] NVARCHAR(250) NULL,
    [LastName] NVARCHAR(250) NULL,
    [DOB] DATE NULL,
    [FenENationalCountryId] INT NULL,
    [FenENationalCountry] VARCHAR(250) NULL,
    [FenXNationalCountry] VARCHAR(250) NULL,
    [FenECitizenshipId] INT NULL,
    [FenECitizenship] VARCHAR(250) NULL,
    [FenXCitizenship] VARCHAR(250) NULL,
    [FenENaicsId] INT NULL,
    [FenENaics] NVARCHAR(500) NULL,
    [FenXNaics] NVARCHAR(500) NULL,
    [FenEPlaceOfBirthId] INT NULL,
    [FenEPlaceOfBirth] NVARCHAR(500) NULL,
    [FenXPlaceOfBirth] NVARCHAR(500) NULL,
    [FenELegalEntityTypeId] INT NULL,
    [FenELegalEntityType] NVARCHAR(500) NULL,
    [FenXLegalEntityType] NVARCHAR(500) NULL,
    [FenETypeOfInvestorId] INT NULL,
    [FenETypeOfInvestor] NVARCHAR(500) NULL,
    [FenXTypeOfInvestor] NVARCHAR(500) NULL,
    [FenESpecializedEddRequiredId] INT NULL,
    [FenESpecializedEddRequired] NVARCHAR(500) NULL,
    [FenXSpecializedEddRequired] NVARCHAR(500) NULL,
    [FenESpecializedEddEntityTypeIds] NVARCHAR(MAX) NULL,
    [FenESpecializedEddEntityType] NVARCHAR(MAX) NULL,
    [FenXSpecializedEddEntityType] NVARCHAR(MAX) NULL,
    [FenEKycLevelId] INT NULL,
    [FenEKycLevel] NVARCHAR(500) NULL,
    [FenXKycLevel] NVARCHAR(500) NULL,
    [KycLevelOverrideComment] NVARCHAR(MAX) NULL,
    [RegistrationNumber] NVARCHAR(500) NULL,
    [AnticipatedActivityOfAccount] NVARCHAR(MAX) NULL,
    [FenERemediationStatusId] INT NULL,
    [FenERemediationStatus] NVARCHAR(500) NULL,
    [FenXRemediationStatus] NVARCHAR(500) NULL,
    [FenETitleId] INT NULL,
    [FenETitle] NVARCHAR(500) NULL,
    [FenXTitle] NVARCHAR(500) NULL,
    [FenEInsiderStatusIds] NVARCHAR(MAX) NULL,
    [FenEInsiderStatus] NVARCHAR(MAX) NULL,
    [FenXInsiderStatus] NVARCHAR(MAX) NULL,
    [CompanyNameInsiderOrShareholderOf] NVARCHAR(500) NULL,
    [Occupation] NVARCHAR(500) NULL,
    [FenEGenderId] INT NULL,
    [FenEGender] NVARCHAR(500) NULL,
    [FenXGender] NVARCHAR(500) NULL,
    [NumberOfIdentificationDocument] NVARCHAR(500) NULL,
    [FenEEmploymentStatusId] INT NULL,
    [FenEEmploymentStatus] NVARCHAR(500) NULL,
    [FenXEmploymentStatus] NVARCHAR(500) NULL,
    [NameOfEmployer] NVARCHAR(500) NULL,
    [NatureOfSelfEmployment] NVARCHAR(MAX) NULL,
    [NationalIdentificationNumber] NVARCHAR(500) NULL,
    [NetWorthOfTheIndividual] DECIMAL(38,10) NULL,
    [LengthOfRelationshipWithScotiabank] NVARCHAR(500) NULL,
    [FenENegativeNewsScreeningConductedId] INT NULL,
    [FenENegativeNewsScreeningConducted] NVARCHAR(500) NULL,
    [FenXNegativeNewsScreeningConducted] NVARCHAR(500) NULL,
    [SummaryOfBusinessActivitiesWithScotia] NVARCHAR(MAX) NULL,
    [PrimaryRevenueGeneratingProductsAndServices] NVARCHAR(MAX) NULL,
    [NationalInsuranceNumber] NVARCHAR(500) NULL,
    [DirectorsIdentificationNumber] NVARCHAR(500) NULL,
    [FenEPepSanctionsId] INT NULL,
    [FenEPepSanctions] NVARCHAR(500) NULL,
    [FenXPepSanctions] NVARCHAR(500) NULL,
    [MarketingInfo] BIT NULL,
    [LastUpdatedBy] NVARCHAR(500) NULL,
    [LoadTimestamp] DATETIME NOT NULL
);

CREATE UNIQUE NONCLUSTERED INDEX IX_E2X_StagingLegalEntityIndividuals_AlternateId
    ON e2x.StagingLegalEntityIndividuals (AlternateId);

CREATE NONCLUSTERED INDEX IX_E2X_StagingLegalEntityIndividuals_LegalEntityId
    ON e2x.StagingLegalEntityIndividuals (LegalEntityId);